import { projectRef, supabase } from './client'

export const sectionKeys=['limited_editions','best_sellers','trending','new_arrivals','oversized_fit','shop_by_design','brand_story'] as const
export type WebsiteSectionKey=typeof sectionKeys[number]
export type WebsiteSettings={footer_tagline:string;footer_description:string}
export type WebsiteSection={section_key:WebsiteSectionKey;heading:string;subheading:string|null;body:string|null;cta_label:string|null;cta_path:string|null;media_path:string|null;media_alt:string|null;media_width:number|null;media_height:number|null;enabled:boolean;sort_order:number;media_url?:string}
export type WebsiteBanner={id:string;image_path:string;mobile_image_path:string|null;alt:string;width:number;height:number;mobile_width:number|null;mobile_height:number|null;eyebrow:string|null;heading:string;description:string|null;cta_label:string|null;cta_path:string|null;enabled:boolean;sort_order:number;image_url?:string;mobile_image_url?:string;bootstrap_preview_url?:string}
export type WebsiteDocument={updated_at:string;settings:WebsiteSettings;sections:WebsiteSection[];banners:WebsiteBanner[]}

const fallbackImages=[
 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1800&q=85',
 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1800&q=85',
 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1800&q=85',
 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=1800&q=85',
]
export const fallbackWebsiteDocument=(updated_at=''):WebsiteDocument=>({updated_at,settings:{footer_tagline:'Less Ordinary. More You.',footer_description:'Limited pieces, made to be remembered.'},banners:fallbackImages.map((image,index)=>({id:`70000000-0000-4000-a000-00000000000${index+1}`,image_path:'',mobile_image_path:null,alt:['Model wearing a white Percent t-shirt','Streetwear model in a fashion campaign','Editorial portrait in a fashion campaign','Minimal apparel campaign in warm tones'][index],width:1800,height:1000,mobile_width:null,mobile_height:null,eyebrow:'NEW DROP',heading:'REDEFINED\nBASICS.',description:'Every Drop is Limited.\nEvery Piece Tells A Story.',cta_label:'SHOP THE DROP',cta_path:'/shop',enabled:true,sort_order:index+1,bootstrap_preview_url:image})),sections:[
 {section_key:'limited_editions',heading:'Limited Editions',subheading:'Creator collaborations, released in limited numbers.',body:null,cta_label:'View All',cta_path:'/shop?tags=limited-edition',media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:1},
 {section_key:'best_sellers',heading:'Best Sellers',subheading:'Most loved pieces, chosen again and again.',body:null,cta_label:'View All',cta_path:'/shop?tags=best-seller',media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:2},
 {section_key:'trending',heading:'Trending',subheading:'Styles getting noticed right now.',body:null,cta_label:'View All',cta_path:'/shop?tags=trending',media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:3},
 {section_key:'new_arrivals',heading:'New Arrivals',subheading:null,body:null,cta_label:'View All',cta_path:'/shop',media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:4},
 {section_key:'oversized_fit',heading:'Oversized Fit',subheading:null,body:'LESS\nORDINARY.\nMORE YOU.',cta_label:'View All',cta_path:'/shop?fit=oversized',media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:5,media_url:'https://images.unsplash.com/photo-1506629905607-d405b7a30db5?auto=format&fit=crop&w=900&q=85'},
 {section_key:'shop_by_design',heading:'Shop by Design',subheading:'Find the artwork that speaks to you.',body:null,cta_label:null,cta_path:null,media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:6},
 {section_key:'brand_story',heading:'What We Do',subheading:null,body:'We create expressive T-shirts in Standard Fit and Oversized Fit, shaped by original design, meaningful collaborations, and the pieces people return to most.',cta_label:'Explore',cta_path:'/about',media_path:null,media_alt:null,media_width:null,media_height:null,enabled:true,sort_order:7},
]})

export const isWebsiteConfigured=(document:WebsiteDocument)=>document.banners.length>0||document.sections.length>0||Boolean(document.settings.footer_tagline.trim()||document.settings.footer_description.trim())
async function media(action:string,extra:Record<string,unknown>={}){const {data,error}=await supabase.functions.invoke('percent-website-media',{body:{action,...extra}});if(error)throw error;return data as {media?:Record<string,string>;path?:string;preview_url?:string}}
function hydrate(document:WebsiteDocument,map:Record<string,string>){return {...document,banners:document.banners.map(b=>({...b,image_url:map[b.image_path],mobile_image_url:b.mobile_image_path?map[b.mobile_image_path]:undefined})),sections:document.sections.map(s=>({...s,media_url:s.media_path?map[s.media_path]:undefined}))}}
export async function loadStorefrontWebsite(){const {data,error}=await supabase.rpc('get_storefront_content');if(error)throw error;const document=normalize(data);if(!isWebsiteConfigured(document))return {managed:false,document:fallbackWebsiteDocument(document.updated_at)};const signed=await media('public_read');return {managed:true,document:hydrate(document,signed.media??{})}}
export async function loadWebsiteEditor(){const {data,error}=await supabase.rpc('get_website_editor');if(error)throw error;const raw=normalize(data);if(!isWebsiteConfigured(raw))return {bootstrap:true,document:fallbackWebsiteDocument(raw.updated_at)};const signed=await media('admin_read');return {bootstrap:false,document:hydrate(raw,signed.media??{})}}
export async function saveWebsite(document:WebsiteDocument){const content={settings:document.settings,sections:document.sections.map(s=>({section_key:s.section_key,heading:s.heading,subheading:s.subheading,body:s.body,cta_label:s.cta_label,cta_path:s.cta_path,media_path:s.media_path,media_alt:s.media_alt,media_width:s.media_width,media_height:s.media_height,enabled:s.enabled,sort_order:s.sort_order})),banners:document.banners.map(b=>({id:b.id,image_path:b.image_path,mobile_image_path:b.mobile_image_path,alt:b.alt,width:b.width,height:b.height,mobile_width:b.mobile_width,mobile_height:b.mobile_height,eyebrow:b.eyebrow,heading:b.heading,description:b.description,cta_label:b.cta_label,cta_path:b.cta_path,enabled:b.enabled,sort_order:b.sort_order}))};const {data,error}=await supabase.rpc('save_website_content',{content,expected_updated_at:document.updated_at});if(error)throw error;return normalize(data)}
export const managedBannerPath=/^banners\/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\/[0-9a-f]{64}\.(jpg|png|webp)$/i
export function validateWebsiteDocument(document:WebsiteDocument){const errors:string[]=[];document.banners.forEach((banner,index)=>{if(!managedBannerPath.test(banner.image_path)||!Number.isInteger(banner.width)||banner.width<1||!Number.isInteger(banner.height)||banner.height<1)errors.push(`Banner ${index+1}: upload a desktop image.`);if(!banner.alt.trim())errors.push(`Banner ${index+1}: add alt text.`);if(!banner.heading.trim())errors.push(`Banner ${index+1}: add a heading.`);if(Boolean(banner.cta_label)!==Boolean(banner.cta_path))errors.push(`Banner ${index+1}: complete both CTA fields.`);if(banner.mobile_image_path&&(!managedBannerPath.test(banner.mobile_image_path)||!Number.isInteger(banner.mobile_width)||Number(banner.mobile_width)<1||!Number.isInteger(banner.mobile_height)||Number(banner.mobile_height)<1))errors.push(`Banner ${index+1}: upload a valid mobile image.`)});document.sections.forEach(section=>{if(!section.heading.trim())errors.push(`${section.section_key}: add a heading.`);if(Boolean(section.cta_label)!==Boolean(section.cta_path))errors.push(`${section.section_key}: complete both CTA fields.`)});return errors}
export async function uploadWebsiteImage(file:File,target_kind:'banner'|'section',target_id:string,size:{width:number;height:number}){const form=new FormData();form.set('action','upload');form.set('target_kind',target_kind);form.set('target_id',target_id);form.set('request_id',crypto.randomUUID());form.set('width',String(size.width));form.set('height',String(size.height));form.set('file',file);const {data,error}=await supabase.functions.invoke('percent-website-media',{body:form});if(error)throw error;const response=data as {path?:string;preview_url?:string;width?:number;height?:number};if(!response.path||!managedBannerPath.test(response.path)&&target_kind==='banner'||!response.preview_url||response.width!==size.width||response.height!==size.height)throw new Error('Upload returned an invalid media record.');return response as {path:string;preview_url:string;width:number;height:number}}
export async function cleanupWebsiteImage(path:string){await media('cleanup',{path})}
function normalize(value:unknown):WebsiteDocument{const v=value as Partial<WebsiteDocument>|null;if(!v?.settings||!Array.isArray(v.sections)||!Array.isArray(v.banners))throw new Error('Website content is unavailable');return {updated_at:String(v.updated_at??''),settings:{footer_tagline:String(v.settings.footer_tagline??''),footer_description:String(v.settings.footer_description??'')},sections:v.sections.map(item=>{const section=item as WebsiteSection&{key?:WebsiteSectionKey};return {...section,section_key:section.section_key??section.key!,enabled:section.enabled??true}}),banners:v.banners.map(item=>{const banner=item as WebsiteBanner;return {...banner,enabled:banner.enabled??true}})}}
export const websiteFunctionUrl=`https://${projectRef}.supabase.co/functions/v1/percent-website-media`


