import { ArrowRight, Headphones, LockKeyhole, ShieldCheck, Truck } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { checkoutAttempt, createCheckoutOrder, resetCheckoutAttempt, type CheckoutOrder } from '../backend/checkout'
import { getProductDetailsById } from '../data/productDetails'
import { formatInr } from '../data/shop'
import { useAccountAddresses } from '../hooks/useAccountAddresses'
import { useCart, type CartLine } from '../hooks/useCommerce'
import { usePercentSession } from '../hooks/usePercentSession'
type ProductRecord=NonNullable<ReturnType<typeof getProductDetailsById>>
interface CheckoutLine{line:CartLine;product:ReturnType<typeof getProductDetailsById>;variant:ProductRecord['variants'][number]|undefined}
const resolveLine=(line:CartLine):CheckoutLine=>{const product=getProductDetailsById(line.productId);return{line,product,variant:product?.variants.find(v=>v.id===line.variantId)}}
function Summary({items,authoritative}:{items:CheckoutLine[];authoritative?:CheckoutOrder}){
 const preview=items.reduce((sum,{line,product,variant})=>sum+(variant?.price??product?.price??0)*line.quantity,0)
 const subtotal=authoritative?.subtotal_paise??preview,shipping=authoritative?.shipping_paise??0,total=authoritative?.total_paise??preview
 return <aside className="checkout-order-summary"><p className="checkout-kicker">Order details</p><h2>Order Summary</h2><div className="checkout-summary-items">{items.map(({line,product,variant})=>{const image=variant?.images?.[0]??product?.images[0];return <article className="checkout-summary-item" key={line.variantId}>{product&&image?<Link to={"/products/"+product.slug} className="checkout-summary-image"><img src={image.src} alt={image.alt}/></Link>:<div className="checkout-summary-image checkout-summary-image-missing">%</div>}<div><strong>{product?.name??'Unavailable design'}</strong><span>{variant?.colour.label??'Unavailable'} · {variant?.size??'Unavailable'}</span><small>Quantity {line.quantity}</small></div><b>{formatInr((variant?.price??0)*line.quantity)}</b></article>})}</div><dl className="checkout-price-summary"><div><dt>Subtotal</dt><dd>{formatInr(subtotal)}</dd></div><div><dt>Shipping</dt><dd>{shipping===0?'Free':formatInr(shipping)}</dd></div><div><dt>Discount</dt><dd>{formatInr(authoritative?.discount_paise??0)}</dd></div></dl><div className="checkout-total"><span>Total</span><strong>{formatInr(total)}</strong><small>Server-authoritative · tax included</small></div><div className="checkout-trust"><div><ShieldCheck/><span><strong>Inventory hold</strong>Exact pieces reserved</span></div><div><Truck/><span><strong>Shipping</strong>Free</span></div><div><Headphones/><span><strong>Support</strong>Help when needed</span></div></div></aside>
}
export function CheckoutPage(){
 const {lines}=useCart(),{user,isAuthenticated,loading:sessionLoading}=usePercentSession(),{addresses,loading:addressesLoading,error:addressError}=useAccountAddresses()
 const navigate=useNavigate(),items=useMemo(()=>lines.map(resolveLine),[lines])
 const [addressId,setAddressId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[order,setOrder]=useState<CheckoutOrder>()
 useEffect(()=>{if(!addressId&&addresses.length)setAddressId((addresses.find(a=>a.isDefault)??addresses[0]).id)},[addresses,addressId])
 useEffect(()=>{const old=document.title;document.title='Checkout | Percent';return()=>{document.title=old}},[])
 const unavailable=items.some(({line,product,variant})=>!product||!variant||product.isSoldOut||!variant.isAvailable||variant.stock<line.quantity)
 const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;if(!isAuthenticated){navigate('/login?returnTo=%2Fcheckout');return}if(!addressId){setError('Choose a saved delivery address before continuing.');return}if(unavailable){setError('One of your items changed. Review your cart.');return}setBusy(true);setError('');try{setOrder(await createCheckoutOrder(lines,addressId,checkoutAttempt(lines,addressId)))}catch(e){setError(e instanceof Error?e.message:'Order could not be created. Nothing was charged.')}finally{setBusy(false)}}
 if(sessionLoading||addressesLoading)return <main className="checkout-page checkout-empty" aria-busy="true"><section><h1>Preparing checkout…</h1><p>Loading your account and saved addresses.</p></section></main>
 if(!lines.length)return <main className="checkout-page checkout-empty"><section><h1>Your Cart Is Empty.</h1><Link to="/shop">Return to Shop <ArrowRight/></Link></section></main>
 if(order)return <main className="checkout-page"><header className="checkout-page-heading"><p className="checkout-kicker">Reservation created</p><h1>Complete Payment Next.</h1><span>Order {order.order_reference} is pending, unpaid and unfulfilled.</span></header><div className="checkout-form-shell"><section className="checkout-panel" aria-live="polite"><h2>Your pieces are held temporarily.</h2><p>Reserved until {order.reservation_expires_at?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(order.reservation_expires_at)):'the server expiry time'}. Payment is not connected and nothing has been charged.</p><p><strong>Status:</strong> {order.status} · {order.payment_status} · {order.fulfillment_status}</p><div className="checkout-promo-control"><Link to={"/orders/"+order.id}>View Order</Link><button type="button" onClick={()=>{resetCheckoutAttempt();setOrder(undefined);setError('A new checkout attempt will request a fresh reservation.')}}>Retry after expiry</button></div></section><Summary items={items} authoritative={order}/></div></main>
 return <main className="checkout-page"><header className="checkout-page-heading"><p className="checkout-kicker">Percent Checkout</p><h1>Reserve Your Pieces</h1></header><ol className="checkout-progress"><li className="is-active"><span>1</span>Account</li><li className="is-active"><span>2</span>Delivery Address</li><li><span>3</span>Payment</li></ol><form className="checkout-form-shell" onSubmit={submit}><div className="checkout-form-sections"><section className="checkout-panel"><div className="checkout-panel-heading"><span>01</span><div><p className="checkout-kicker">Authenticated account</p><h2>Contact Information</h2></div></div>{isAuthenticated?<p>{user?.displayName}<br/>{user?.email}</p>:<p><Link to="/login?returnTo=%2Fcheckout">Sign in to continue <ArrowRight/></Link></p>}</section><section className="checkout-panel"><div className="checkout-panel-heading"><span>02</span><div><p className="checkout-kicker">Saved account address</p><h2>Delivery Address</h2></div></div>{addressError&&<p role="alert">{addressError}</p>}{addresses.length?<div className="account-address-list">{addresses.map(address=><label className="account-address-card" key={address.id}><input type="radio" name="shipping-address" value={address.id} checked={addressId===address.id} onChange={()=>{setAddressId(address.id);resetCheckoutAttempt();setError('')}}/><strong>{address.label}{address.isDefault?' · Default':''}</strong><span>{address.fullName}, {address.addressLine1}, {address.city}, {address.state} {address.pinCode}</span></label>)}</div>:<p>No saved delivery address. <Link to="/profile/address">Add an address <ArrowRight/></Link></p>}</section><section className="checkout-panel checkout-promo"><div><p className="checkout-kicker">Promo codes</p><h2>Coming Later</h2></div><p>Discount codes are unavailable until server-side coupon support is enabled.</p></section></div><Summary items={items}/><section className="checkout-payment"><div className="checkout-payment-copy"><span><LockKeyhole/></span><div><p className="checkout-kicker">Secure reservation</p><h2>Reserve Inventory</h2><small>Creates a pending unpaid order. Payment follows in Phase 4D.</small></div></div>{error&&<p className="checkout-payment-error" role="alert">{error}</p>}<button type="submit" className="checkout-pay-button" disabled={busy||!isAuthenticated||!addressId||unavailable}>{busy?'Creating order…':'Create Pending Order'} <ArrowRight/></button><div className="checkout-payment-meta"><span><ShieldCheck/> Nothing charged</span><span>Shipping: Free</span></div></section></form></main>
}
