import fs from 'node:fs'
import { createHash } from 'node:crypto'
const { products, blogArticles, summary } = JSON.parse(fs.readFileSync('docs/backend/catalog-audit.json','utf8'))
const id = key => { const h=createHash('sha256').update('percent:phase1:'+key).digest('hex'); return `${h.slice(0,8)}-${h.slice(8,12)}-4${h.slice(13,16)}-a${h.slice(17,20)}-${h.slice(20,32)}` }
const literal = v => v===null||v===undefined ? 'null' : typeof v==='boolean'||typeof v==='number' ? String(v) : `'${String(v).replaceAll("'","''")}'`
const lines=['-- Generated by node scripts/prepare-seed.mjs. Draft catalog only; NO demo inventory/users/orders/reviews.', 'begin;']
function insert(table,values) { lines.push(`insert into public.${table} (${Object.keys(values).join(',')}) values (${Object.values(values).map(literal).join(',')}) on conflict do nothing;`) }
insert('categories',{id:id('category:t-shirts'),slug:'t-shirts',name:'T-Shirts'})
for(const c of summary.colors) insert('colours',{id:id(c.id),slug:c.slug,label:c.label,swatch_value:c.swatchValue})
for(const t of summary.tags) insert('tags',{id:id(t.id),slug:t.slug,name:t.name,group_name:t.group,is_filterable:t.isFilterable,active:t.isActive,display_order:t.displayOrder})
for(const p of products) {
 insert('products',{id:id(p.id),legacy_id:p.id,design_code:p.id,slug:p.slug,name:p.name,short_description:p.shortDescription,full_description:p.fullDescription,category_id:id('category:t-shirts'),fit_type:p.fitType,status:'draft',is_visible:false,is_shop_available:p.isShopAvailable,is_limited:p.isLimitedEdition,total_produced:100,price_paise:p.price*100,compare_at_price_paise:p.compareAtPrice===undefined?null:p.compareAtPrice*100,material:p.material,style:p.style,care_instructions:p.careInstructions,shipping_and_returns:p.shippingAndReturns,collaborator_name:p.collaboratorName,collaboration_title:p.collaborationTitle,collaboration_description:p.collaborationDescription,collaborator_image_url:p.collaboratorImage?.src,featured:p.featured,display_order:p.displayOrder,launch_at:p.launchDate})
 for(const t of p.tags) insert('product_tags',{product_id:id(p.id),tag_id:id(t.id)})
 for(const [n,im] of p.images.entries()) insert('product_images',{id:id(p.id+':image:'+n),product_id:id(p.id),url:im.src,alt:im.alt,width:im.width,height:im.height,role:im.role,sort_order:n})
 for(const v of p.variants) {
  insert('product_variants',{id:id(v.id),legacy_id:v.id,product_id:id(p.id),colour_id:id(v.colour.id),size:v.size,sku:v.id.toUpperCase(),price_paise:v.price*100,compare_at_price_paise:v.compareAtPrice===undefined?null:v.compareAtPrice*100})
  for(const [n,im] of v.images.entries()) { const pi=p.images.findIndex(x=>x.src===im.src); if(pi<0) throw Error('Unmapped image'); insert('variant_images',{variant_id:id(v.id),product_id:id(p.id),image_id:id(p.id+':image:'+pi),sort_order:n}) }
 }
}
for(const p of blogArticles) {
 insert('blog_posts',{id:id('blog:'+p.slug),slug:p.slug,title:p.title,excerpt:p.excerpt,introduction:p.introduction,category:p.category,author:p.author,published_at:p.date+'T00:00:00+05:30',status:'draft',featured:p.featured,pull_quote:p.pullQuote})
 for(const [n,s] of p.sections.entries()) insert('blog_sections',{id:id('section:'+p.slug+':'+n),post_id:id('blog:'+p.slug),heading:s.heading,paragraphs:JSON.stringify(s.paragraphs),sort_order:n})
 for(const [role,im] of [['primary',p.image],['secondary',p.secondaryImage]]) if(im) insert('blog_images',{id:id('blog-image:'+p.slug+':'+role),post_id:id('blog:'+p.slug),role,url:im.src,alt:im.alt,width:im.width,height:im.height})
}
lines.push('commit;','')
fs.writeFileSync('supabase/seed.sql',lines.join('\n'))
console.log(`Prepared ${products.length} draft products, ${summary.catalogVariants} variants, ${blogArticles.length} draft posts; zero physical inventory units.`)
