import { useEffect,useState } from 'react'
import { ArrowLeft,Heart,MapPin,MessageSquare,PackageSearch,RefreshCw,ShoppingBag,UserRound } from 'lucide-react'
import { Link,useOutletContext,useParams } from 'react-router-dom'
import type { AdminIdentity } from '../../components/admin/AdminRouteGuard'
import { AdminEmptyState,AdminPageHeader,AdminStatCard,AdminStatusBadge } from '../../components/admin/AdminComponents'
import { loadAdminCustomer } from '../../backend/admin/customers'
import type { CustomerDetail } from '../../backend/admin/customer-model'
import { formatInrFromPaise } from '../../data/money'
import './customers.css'

const date=(value:string|null,withTime=false)=>value?new Intl.DateTimeFormat('en-IN',withTime?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'}).format(new Date(value)):'—'

export function AdminCustomerDetail(){
 const {id=''}=useParams(),{user}=useOutletContext<AdminIdentity>(),[customer,setCustomer]=useState<CustomerDetail|null>(),[error,setError]=useState(false),[revision,setRevision]=useState(0)
 useEffect(()=>{const controller=new AbortController();Promise.resolve().then(()=>loadAdminCustomer(user.id,id,controller.signal)).then(data=>{if(!controller.signal.aborted){setCustomer(data);setError(false)}}).catch(()=>{if(!controller.signal.aborted){setCustomer(null);setError(true)}});return()=>controller.abort()},[user.id,id,revision])
 if(customer===undefined)return <div className="admin-loading" aria-busy="true"><p role="status">Loading customer…</p></div>
 if(error)return <section className="admin-panel customer-state" role="alert"><AdminEmptyState icon={UserRound} title="Unable to load this customer."/><button className="admin-button" onClick={()=>{setCustomer(undefined);setRevision(v=>v+1)}}>Retry <RefreshCw/></button></section>
 if(!customer)return <section className="admin-panel customer-state"><AdminEmptyState icon={UserRound} title="Customer not found." description="This ID is invalid, unavailable, or belongs to a staff-only account."/><Link className="admin-button" to="/admin/customers"><ArrowLeft/> Back to customers</Link></section>
 const {profile,metrics}=customer
 return <><Link className="customer-back" to="/admin/customers"><ArrowLeft/> Back to customers</Link><AdminPageHeader title={profile.display_name} description="Read-only customer profile, activity and order value."/>
  <section className="admin-panel customer-hero"><div className="customer-avatar" aria-hidden="true">{profile.display_name.slice(0,1).toUpperCase()}</div><div><span>Customer profile</span><h2>{profile.display_name}</h2><p>{profile.email||'No Auth email'} · {profile.phone||'No phone provided'}</p></div><AdminStatusBadge status={profile.account_role??'customer'}/></section>
  <div className="admin-stats customer-detail-stats"><AdminStatCard label="Orders" value={String(metrics.order_count)} note="All recorded orders" icon={ShoppingBag}/><AdminStatCard label="Lifetime Value" value={formatInrFromPaise(metrics.lifetime_order_value_paise)} note="Non-cancelled orders" icon={PackageSearch}/><AdminStatCard label="Average Order" value={formatInrFromPaise(metrics.average_order_value_paise)} note="Non-cancelled orders" icon={PackageSearch}/><AdminStatCard label="Latest Order" value={date(metrics.latest_order_at)} note="Any lifecycle state" icon={ShoppingBag}/></div>
  <div className="customer-detail-grid"><main>
   <section className="admin-panel customer-section"><header><UserRound/><div><h2>Customer Profile</h2><p>Auth-backed account information.</p></div></header><dl className="customer-profile-grid"><div><dt>Display name</dt><dd>{profile.display_name}</dd></div><div><dt>First name</dt><dd>{profile.first_name||'Not provided'}</dd></div><div><dt>Last name</dt><dd>{profile.last_name||'Not provided'}</dd></div><div><dt>Email</dt><dd>{profile.email||'Not provided'}</dd></div><div><dt>Phone</dt><dd>{profile.phone||'Not provided'}</dd></div><div><dt>Joined</dt><dd>{date(profile.created_at,true)}</dd></div></dl></section>
   <section className="admin-panel customer-section"><header><ShoppingBag/><div><h2>Orders</h2><p>All recorded orders; value metrics exclude cancelled orders.</p></div></header>{customer.orders.length?<div className="customer-order-list">{customer.orders.map(order=><article key={order.id}><div><Link to={`/admin/orders/${order.id}`}>{order.order_reference}</Link><time dateTime={order.created_at}>{date(order.created_at,true)}</time></div><strong>{formatInrFromPaise(order.total_paise)}</strong><div className="customer-order-status"><AdminStatusBadge status={order.status}/><AdminStatusBadge status={order.payment_status}/><AdminStatusBadge status={order.fulfillment_status}/></div>{order.active_reservation_count>0&&<small>{order.active_reservation_count} piece{order.active_reservation_count===1?'':'s'} reserved until {date(order.reservation_expires_at,true)}</small>}</article>)}</div>:<AdminEmptyState icon={ShoppingBag} title="No orders recorded."/>}</section>
   <section className="admin-panel customer-section"><header><MessageSquare/><div><h2>Reviews</h2><p>Real review submissions and moderation state.</p></div></header>{customer.reviews.length?<div className="customer-review-list">{customer.reviews.map(review=><article key={review.id}><div><strong>{review.product_name||'Product unavailable'}</strong><span>{review.rating}/5</span></div><p>{review.title||'Untitled review'}</p><small>{date(review.created_at,true)}</small><AdminStatusBadge status={review.status}/></article>)}</div>:<AdminEmptyState icon={MessageSquare} title="No reviews submitted."/>}</section>
  </main><aside>
   <section className="admin-panel customer-section"><header><MapPin/><div><h2>Saved Addresses</h2><p>{metrics.address_count} saved</p></div></header>{customer.addresses.length?<div className="customer-addresses">{customer.addresses.map(address=><address key={address.id}><strong>{address.label}{address.is_default?' · Default':''}</strong><span>{address.full_name}</span><span>{address.address_line1}</span>{address.address_line2&&<span>{address.address_line2}</span>}<span>{address.city}, {address.state} {address.pin_code}</span><span>{address.country}</span><small>{address.phone}</small></address>)}</div>:<AdminEmptyState icon={MapPin} title="No saved addresses."/>}</section>
   <section className="admin-panel customer-section"><header><Heart/><div><h2>Wishlist</h2><p>{metrics.wishlist_count} saved</p></div></header>{customer.wishlist.length?<ul className="customer-wishlist">{customer.wishlist.map(item=><li key={item.product_id}>{item.product_slug?<Link to={`/products/${item.product_slug}`} target="_blank" rel="noopener noreferrer">{item.product_name||'Product'}</Link>:<span>{item.product_name||'Product unavailable'}</span>}<time dateTime={item.created_at}>{date(item.created_at)}</time></li>)}</ul>:<AdminEmptyState icon={Heart} title="No wishlist items."/>}</section>
  </aside></div></>
}
