/* eslint-disable react-hooks/set-state-in-effect */
import { useCallback, useEffect, useRef, useState, type ChangeEvent, type ReactNode } from 'react'
import { ArrowDown, ArrowUp, Eye, ImagePlus, Plus, RotateCcw, Save, Trash2 } from 'lucide-react'
import { useBeforeUnload, useBlocker, useParams } from 'react-router-dom'
import { cleanupWebsiteImage, defaultGlobalSettings, listWebsiteMedia, loadWebsiteEditor, saveWebsiteGlobals, uploadWebsiteLibraryImage, type SocialLink, type WebsiteDocument, type WebsiteMediaAsset } from '../../backend/website'
import './website-editor.css'
import './global-website-editor.css'

type GlobalModule='navbar'|'branding'|'colors'|'typography'|'social-links'|'media'
const labels:Record<GlobalModule,string>={navbar:'Navbar',branding:'Branding',colors:'Colors',typography:'Typography','social-links':'Social Links',media:'Media Library'}
const errorText=(value:unknown)=>value instanceof Error?value.message:'Unable to complete this request.'
const snap=(document:WebsiteDocument)=>JSON.stringify({navbar_items:document.settings.navbar_items,branding:document.settings.branding,colors:document.settings.colors,typography:document.settings.typography,social_links:document.settings.social_links},(key,value)=>key.endsWith('_url')?undefined:value)
const dimensions=(file:File)=>new Promise<{width:number;height:number}>((resolve,reject)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{resolve({width:image.naturalWidth,height:image.naturalHeight});URL.revokeObjectURL(url)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Select a readable JPG, PNG, or WebP image.'))};image.src=url})

export function AdminGlobalWebsiteEditor(){
 const requested=useParams().section as GlobalModule
 const module:GlobalModule=Object.hasOwn(labels,requested)?requested:'navbar'
 const [document,setDocument]=useState<WebsiteDocument|null>(null),[baseline,setBaseline]=useState(''),[busy,setBusy]=useState(true),[message,setMessage]=useState(''),[error,setError]=useState(false),[assets,setAssets]=useState<WebsiteMediaAsset[]>([]),[obsolete,setObsolete]=useState<string[]>([])
 const frame=useRef<HTMLIFrameElement>(null),allow=useRef(false)
 const dirty=!!document&&snap(document)!==baseline
 const blocker=useBlocker(({currentLocation,nextLocation})=>!allow.current&&(dirty||busy)&&currentLocation.pathname!==nextLocation.pathname)
 useBeforeUnload(event=>{if(dirty||busy){event.preventDefault();event.returnValue=''}})
 const load=useCallback(async()=>{setBusy(true);try{const result=await loadWebsiteEditor();setDocument(result.document);setBaseline(snap(result.document));setMessage('');setError(false);if(module==='media')setAssets(await listWebsiteMedia())}catch(e){setMessage(errorText(e));setError(true)}finally{setBusy(false)}},[module])
 useEffect(()=>{void load()},[load])
 useEffect(()=>{if(document)frame.current?.contentWindow?.postMessage({type:'percent-website-preview-draft',document},window.location.origin)},[document])
 const patchSettings=(patch:Partial<WebsiteDocument['settings']>)=>setDocument(current=>current?{...current,settings:{...current.settings,...patch}}:current)
 const save=async()=>{if(!document)return;setBusy(true);setMessage('');try{await saveWebsiteGlobals(document);const refreshed=await loadWebsiteEditor();setDocument(refreshed.document);setBaseline(snap(refreshed.document));setMessage('Global settings saved.');setError(false);await Promise.allSettled([...new Set(obsolete)].map(cleanupWebsiteImage));setObsolete([])}catch(e){const text=errorText(e);setMessage(text.toLowerCase().includes('changed')?'This content changed elsewhere. Reload before saving again.':text);setError(true)}finally{setBusy(false)}}
 const uploadBrand=async(event:ChangeEvent<HTMLInputElement>,kind:'logo'|'favicon')=>{const file=event.target.files?.[0];event.target.value='';if(!file||!document)return;setBusy(true);try{const size=await dimensions(file),result=await uploadWebsiteLibraryImage(file,size,'branding'),brand=document.settings.branding;const old=kind==='logo'?brand.logo_path:brand.favicon_path;if(old)setObsolete(items=>[...items,old]);patchSettings({branding:kind==='logo'?{...brand,logo_path:result.path,logo_url:result.preview_url,logo_alt:brand.logo_alt||brand.display_name,logo_width:result.width,logo_height:result.height}:{...brand,favicon_path:result.path,favicon_url:result.preview_url}});setMessage('Image uploaded. Save changes to publish it.');setError(false)}catch(e){setMessage(errorText(e));setError(true)}finally{setBusy(false)}}
 const refreshAssets=async()=>setAssets(await listWebsiteMedia())
 if(!document)return <section className="website-editor website-loading"><h1>{labels[module]}</h1><p>{busy?'Loading global settings…':message}</p></section>
 return <section className="website-editor global-editor"><header className="website-page-head"><div><h1>{labels[module]}</h1><p>Manage the shared storefront experience.</p></div><p>Your brand. Your rules.<br/>Changes apply across the storefront.</p></header><div className="website-toolbar"><div className="website-toolbar-title"><span>Website Editor</span><strong>{labels[module]}</strong></div><div className="website-toolbar-actions"><span className={`save-state ${dirty?'is-dirty':error?'is-error':''}`}><i/>{busy?'Working…':dirty?'Unsaved changes':error?'Action failed':'Saved'}</span>{module!=='media'&&<button className="website-button" onClick={()=>frame.current?.scrollIntoView({block:'center'})}><Eye/>Preview</button>}<button className="website-button primary" disabled={busy||!dirty||module==='media'} onClick={()=>void save()}><Save/>Save Changes</button></div></div>{message&&<p className={`website-notice ${error?'error':'success'}`} role={error?'alert':'status'}>{message}</p>}
 <div className={`global-editor-grid ${module==='media'?'media-mode':''}`}><main className="designer-card global-control-card">{module==='navbar'&&<NavbarEditor document={document} setDocument={setDocument}/>} {module==='branding'&&<BrandingEditor document={document} patch={patchSettings} upload={uploadBrand}/>} {module==='colors'&&<ColorsEditor document={document} patch={patchSettings}/>} {module==='typography'&&<TypographyEditor document={document} patch={patchSettings}/>} {module==='social-links'&&<SocialEditor document={document} patch={patchSettings}/>} {module==='media'&&<MediaLibrary assets={assets} busy={busy} setBusy={setBusy} setMessage={setMessage} setError={setError} refresh={refreshAssets}/>}</main>{module!=='media'&&<aside className="live-preview global-preview"><div className="live-preview-head"><div><h2>Live Storefront Preview</h2><p>Uses the real Navbar, page, and Footer components.</p></div></div><div className="preview-stage"><iframe ref={frame} title={`${labels[module]} storefront preview`} src="/admin/website/preview" onLoad={()=>frame.current?.contentWindow?.postMessage({type:'percent-website-preview-draft',document},window.location.origin)}/></div></aside>}</div>
 {blocker.state==='blocked'&&<div className="website-blocker" role="dialog" aria-modal="true"><p>Discard unsaved global changes?</p><button className="website-button" onClick={()=>blocker.reset()}>Keep editing</button><button className="website-button danger" onClick={()=>{allow.current=true;blocker.proceed()}}>Discard</button></div>}</section>
}

function NavbarEditor({document,setDocument}:{document:WebsiteDocument;setDocument:(value:WebsiteDocument)=>void}){const items=document.settings.navbar_items;const update=(index:number,patch:Partial<(typeof items)[number]>)=>setDocument({...document,settings:{...document.settings,navbar_items:items.map((item,i)=>i===index?{...item,...patch}:item)}});const move=(index:number,offset:number)=>{const next=items.slice(),target=index+offset;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setDocument({...document,settings:{...document.settings,navbar_items:next.map((item,i)=>({...item,sort_order:i+1}))}})};return <><EditorHead title="Navbar" copy="Edit safe content links. Search, profile, cart, and commerce controls remain protected."/><div className="global-list">{items.map((item,index)=><article key={item.id}><div className="field-pair"><Field label="Label"><input maxLength={40} value={item.label} onChange={e=>update(index,{label:e.target.value})}/></Field><Field label="Internal path"><input value={item.path} onChange={e=>update(index,{path:e.target.value})}/></Field></div><div className="global-row-actions"><label><input type="checkbox" checked={item.enabled} onChange={e=>update(index,{enabled:e.target.checked})}/> Visible</label><button aria-label={`Move ${item.label} up`} disabled={!index} onClick={()=>move(index,-1)}><ArrowUp/></button><button aria-label={`Move ${item.label} down`} disabled={index===items.length-1} onClick={()=>move(index,1)}><ArrowDown/></button></div></article>)}</div></>}
function BrandingEditor({document,patch,upload}:{document:WebsiteDocument;patch:(value:Partial<WebsiteDocument['settings']>)=>void;upload:(event:ChangeEvent<HTMLInputElement>,kind:'logo'|'favicon')=>Promise<void>}){const b=document.settings.branding,u=(value:Partial<typeof b>)=>patch({branding:{...b,...value}});return <><EditorHead title="Branding" copy="Shared wordmark, tagline, logo, and browser icon."/><div className="designer-fields"><Field label="Display name"><input maxLength={40} value={b.display_name} onChange={e=>u({display_name:e.target.value})}/></Field><Field label="Tagline"><input maxLength={100} value={b.tagline} onChange={e=>u({tagline:e.target.value})}/></Field><MediaInput title="Primary logo" preview={b.logo_url} onChange={e=>void upload(e,'logo')} onRemove={()=>u({logo_path:null,logo_url:undefined,logo_alt:null,logo_width:null,logo_height:null})}/>{b.logo_path&&<Field label="Logo alt text"><input maxLength={160} value={b.logo_alt??''} onChange={e=>u({logo_alt:e.target.value})}/></Field>}<MediaInput title="Favicon" preview={b.favicon_url} onChange={e=>void upload(e,'favicon')} onRemove={()=>u({favicon_path:null,favicon_url:undefined})}/></div></>}
function ColorsEditor({document,patch}:{document:WebsiteDocument;patch:(value:Partial<WebsiteDocument['settings']>)=>void}){const colors=document.settings.colors,defaults=defaultGlobalSettings().colors;return <><EditorHead title="Global Colors" copy="Controlled storefront design tokens. Admin colors remain unchanged."/><button className="website-button" onClick={()=>patch({colors:defaults})}><RotateCcw/>Reset Percent defaults</button><div className="color-grid">{Object.entries(colors).map(([key,value])=><Field key={key} label={key.replaceAll('_',' ')}><span className="color-control"><input type="color" value={value} onChange={e=>patch({colors:{...colors,[key]:e.target.value}})}/><input pattern="#[0-9a-fA-F]{6}" value={value} onChange={e=>patch({colors:{...colors,[key]:e.target.value}})}/></span></Field>)}</div></>}
function TypographyEditor({document,patch}:{document:WebsiteDocument;patch:(value:Partial<WebsiteDocument['settings']>)=>void}){const t=document.settings.typography,u=(value:Partial<typeof t>)=>patch({typography:{...t,...value}}),fonts=['Inter','Georgia','system-ui'] as const;return <><EditorHead title="Global Typography" copy="Choose from the approved bundled font registry."/><div className="designer-fields">{(['display_family','heading_family','body_family','ui_family'] as const).map(key=><Field key={key} label={key.replaceAll('_',' ')}><select value={t[key]} onChange={e=>u({[key]:e.target.value})}>{fonts.map(font=><option key={font}>{font}</option>)}</select></Field>)}<div className="field-pair"><Field label="Heading weight"><select value={t.heading_weight} onChange={e=>u({heading_weight:Number(e.target.value) as typeof t.heading_weight})}>{[400,500,600,700,800].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Body weight"><select value={t.body_weight} onChange={e=>u({body_weight:Number(e.target.value) as typeof t.body_weight})}>{[400,500,600,700].map(v=><option key={v}>{v}</option>)}</select></Field></div><Field label={`Letter spacing (${t.letter_spacing.toFixed(2)}em)`}><input type="range" min="-0.05" max="0.30" step="0.01" value={t.letter_spacing} onChange={e=>u({letter_spacing:Number(e.target.value)})}/></Field></div></>}
function SocialEditor({document,patch}:{document:WebsiteDocument;patch:(value:Partial<WebsiteDocument['settings']>)=>void}){const items=document.settings.social_links,available=(['instagram','facebook','x','youtube','pinterest','linkedin'] as SocialLink['platform'][]).filter(p=>!items.some(i=>i.platform===p));const set=(next:SocialLink[])=>patch({social_links:next.map((item,index)=>({...item,sort_order:index+1}))});return <><EditorHead title="Social Links" copy="Enabled links appear in the storefront Footer with safe external-link protection."/><div className="global-list">{items.map((item,index)=><article key={item.platform}><strong>{item.platform==='x'?'X':item.platform[0].toUpperCase()+item.platform.slice(1)}</strong><Field label="HTTPS URL"><input type="url" value={item.url} onChange={e=>set(items.map((v,i)=>i===index?{...v,url:e.target.value}:v))}/></Field><div className="global-row-actions"><label><input type="checkbox" checked={item.enabled} onChange={e=>set(items.map((v,i)=>i===index?{...v,enabled:e.target.checked}:v))}/> Enabled</label><button aria-label={`Remove ${item.platform}`} onClick={()=>set(items.filter((_,i)=>i!==index))}><Trash2/></button></div></article>)}</div>{available.length>0&&<button className="website-button" onClick={()=>set([...items,{platform:available[0],url:`https://${available[0]}.com/`,enabled:false,sort_order:items.length+1}])}><Plus/>Add {available[0]}</button>}</>}
function MediaLibrary({assets,busy,setBusy,setMessage,setError,refresh}:{assets:WebsiteMediaAsset[];busy:boolean;setBusy:(v:boolean)=>void;setMessage:(v:string)=>void;setError:(v:boolean)=>void;refresh:()=>Promise<void>}){const upload=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);try{await uploadWebsiteLibraryImage(file,await dimensions(file));await refresh();setMessage('Media uploaded.');setError(false)}catch(e){setMessage(errorText(e));setError(true)}finally{setBusy(false)}};const remove=async(asset:WebsiteMediaAsset)=>{setBusy(true);try{await cleanupWebsiteImage(asset.path);await refresh();setMessage('Unreferenced media removed.');setError(false)}catch(e){setMessage(errorText(e));setError(true)}finally{setBusy(false)}};return <><EditorHead title="Media Library" copy="Managed assets in the private percent-website-media bucket."/><label className="website-button media-upload"><ImagePlus/>Upload image<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void upload(e)}/></label>{assets.length===0?<div className="designer-empty"><p>No managed Website media found.</p></div>:<div className="media-library-grid">{assets.map(asset=><article key={asset.path}><img src={asset.preview_url} alt=""/><div><strong>{asset.path.split('/').at(-1)}</strong><small>{asset.mime_type} · {Math.ceil(asset.size/1024)} KB</small><span>{asset.referenced?'In use':'Unreferenced'}</span></div><button disabled={asset.referenced||busy} aria-label={`Delete ${asset.path}`} onClick={()=>void remove(asset)}><Trash2/></button></article>)}</div>}</>}
function EditorHead({title,copy}:{title:string;copy:string}){return <div className="designer-card-head"><div><h2>{title}</h2><p>{copy}</p></div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="designer-field"><span>{label}</span>{children}</label>}
function MediaInput({title,preview,onChange,onRemove}:{title:string;preview?:string;onChange:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <div className="global-media-input"><span>{title}</span>{preview?<img src={preview} alt=""/>:<div>No managed image selected</div>}<p><label className="website-button"><ImagePlus/>Choose image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={onChange}/></label>{preview&&<button className="website-button danger" onClick={onRemove}><Trash2/>Remove</button>}</p></div>}
