import { useEffect,useState } from 'react'
import { Link,useOutletContext } from 'react-router-dom'
import { CalendarPlus,IndianRupee,RefreshCw,Search,ShoppingBag,Users } from 'lucide-react'
import type { AdminIdentity } from '../../components/admin/AdminRouteGuard'
import { AdminEmptyState,AdminPageHeader,AdminStatCard,AdminStatusBadge } from '../../components/admin/AdminComponents'
import { listAdminCustomers } from '../../backend/admin/customers'
import { customerPageSize,emptyCustomerFilters,type AdminCustomerSummary,type CustomerFilters,type CustomerListResult } from '../../backend/admin/customer-model'
import { formatInrFromPaise } from '../../data/money'
import './customers.css'

const date=(value:string|null)=>value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(value)):'—'
const filters:Array<[CustomerFilters['filter'],string]>=[['all','All Customers'],['has_orders','Has Orders'],['no_orders','No Orders'],['recently_joined','Recently Joined']]
const sorts:Array<[CustomerFilters['sort'],string]>=[['newest','Newest customers'],['oldest','Oldest customers'],['most_orders','Most orders'],['highest_value','Highest lifetime value'],['latest_order','Latest order']]

function CustomerCards({items}:{items:AdminCustomerSummary[]}){return <div className="customer-cards">{items.map(customer=><article key={customer.id}><header><div className="customer-avatar" aria-hidden="true">{customer.display_name.slice(0,1).toUpperCase()}</div><div><Link to={`/admin/customers/${customer.id}`}>{customer.display_name}</Link><small>{customer.email||'No Auth email'}</small></div><AdminStatusBadge status={customer.account_role??'customer'}/></header><dl><div><dt>Phone</dt><dd>{customer.phone||'Not provided'}</dd></div><div><dt>Joined</dt><dd>{date(customer.created_at)}</dd></div><div><dt>Orders</dt><dd>{customer.order_count}</dd></div><div><dt>Lifetime value</dt><dd>{formatInrFromPaise(customer.lifetime_order_value_paise)}</dd></div><div><dt>Latest order</dt><dd>{date(customer.latest_order_at)}</dd></div><div><dt>Addresses / Reviews</dt><dd>{customer.address_count} / {customer.review_count}</dd></div></dl><Link className="customer-view" to={`/admin/customers/${customer.id}`}>View customer</Link></article>)}</div>}

export function AdminCustomers(){
 const {user}=useOutletContext<AdminIdentity>(),[search,setSearch]=useState(''),[filtersState,setFilters]=useState(emptyCustomerFilters),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[result,setResult]=useState<CustomerListResult>(),[error,setError]=useState(false)
 useEffect(()=>{const timer=setTimeout(()=>{setFilters(current=>({...current,search}));setPage(1)},250);return()=>clearTimeout(timer)},[search])
 useEffect(()=>{const controller=new AbortController();Promise.resolve().then(()=>listAdminCustomers(user.id,filtersState,page,controller.signal)).then(data=>{if(!controller.signal.aborted){setResult(data);setError(false)}}).catch(()=>{if(!controller.signal.aborted){setResult(undefined);setError(true)}});return()=>controller.abort()},[user.id,filtersState,page,revision])
 const metrics=result?.metrics,pages=Math.max(1,Math.ceil((result?.count??0)/customerPageSize))
 const update=<K extends keyof CustomerFilters>(key:K,value:CustomerFilters[K])=>{setResult(undefined);setFilters(current=>({...current,[key]:value}));setPage(1)}
 return <><AdminPageHeader title="Customers" description="Understand real Percent accounts, order history and customer activity."/>
  <div className="admin-stats customer-stats"><AdminStatCard label="Total Customers" value={String(metrics?.total_customers??0)} note="Eligible customer accounts" icon={Users}/><AdminStatCard label="With Orders" value={String(metrics?.customers_with_orders??0)} note="At least one recorded order" icon={ShoppingBag}/><AdminStatCard label="New Customers" value={String(metrics?.new_customers_current_utc_month??0)} note="Current UTC calendar month" icon={CalendarPlus}/><AdminStatCard label="Customer Order Value" value={formatInrFromPaise(metrics?.total_customer_order_value_paise??0)} note="Non-cancelled orders" icon={IndianRupee}/></div>
  <section className="admin-panel customer-list"><header><div><h2>Customer Accounts</h2><p>Read-only Auth-backed profiles and real activity.</p></div><button className="admin-icon-button" aria-label="Refresh customers" onClick={()=>{setResult(undefined);setRevision(v=>v+1)}}><RefreshCw/></button></header>
   <div className="customer-toolbar"><label className="customer-search"><Search/><span className="sr-only">Search customers</span><input aria-label="Search customers" placeholder="Name, email, phone, or order reference…" value={search} onChange={e=>setSearch(e.target.value)}/></label><label><span>Customer filter</span><select value={filtersState.filter} onChange={e=>update('filter',e.target.value as CustomerFilters['filter'])}>{filters.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label><span>Sort</span><select value={filtersState.sort} onChange={e=>update('sort',e.target.value as CustomerFilters['sort'])}>{sorts.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>
   {!result&&!error?<div className="admin-loading" aria-busy="true"><p role="status">Loading customers…</p></div>:error?<div className="customer-state" role="alert"><AdminEmptyState icon={Users} title="Unable to load customers." description="The customer service did not return a usable response."/><button className="admin-button" onClick={()=>{setError(false);setRevision(v=>v+1)}}>Retry</button></div>:result&&!result.items.length?<AdminEmptyState icon={Search} title={filtersState.search||filtersState.filter!=='all'?'No matching customers.':'No customers yet.'} description={filtersState.search||filtersState.filter!=='all'?'Try another search or filter.':'Eligible customer accounts will appear here.'}/>:result&&<><div className="customer-table"><table><thead><tr>{['Customer','Role','Phone','Joined','Orders','Lifetime Value','Latest Order','Addresses','Reviews',''].map(label=><th key={label} scope="col">{label||<span className="sr-only">Action</span>}</th>)}</tr></thead><tbody>{result.items.map(customer=><tr key={customer.id}><td><div className="customer-identity"><span className="customer-avatar" aria-hidden="true">{customer.display_name.slice(0,1).toUpperCase()}</span><div><strong>{customer.display_name}</strong><small>{customer.email||'No Auth email'}</small></div></div></td><td><AdminStatusBadge status={customer.account_role??'customer'}/></td><td>{customer.phone||'—'}</td><td>{date(customer.created_at)}</td><td>{customer.order_count}</td><td>{formatInrFromPaise(customer.lifetime_order_value_paise)}</td><td>{date(customer.latest_order_at)}</td><td>{customer.address_count}</td><td>{customer.review_count}</td><td><Link aria-label={`View ${customer.display_name}`} to={`/admin/customers/${customer.id}`}>View</Link></td></tr>)}</tbody></table></div><CustomerCards items={result.items}/><footer><span>{result.count?`Showing ${(page-1)*customerPageSize+1}–${Math.min(page*customerPageSize,result.count)} of ${result.count}`:'0 customers'}</span><nav aria-label="Customers pagination"><button disabled={page<=1} onClick={()=>{setResult(undefined);setPage(v=>v-1)}}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>{setResult(undefined);setPage(v=>v+1)}}>Next</button></nav></footer></>}
  </section></>
}
