import { useEffect, useRef, useState, type ReactNode } from 'react'
import { Link, useBeforeUnload, useBlocker, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, ArrowDown, ArrowUp, CheckCircle2, ImagePlus, Package, Plus, Save, Send, Trash2, XCircle } from 'lucide-react'
import { AdminPageHeader, AdminStatusBadge } from '../../components/admin/AdminComponents'
import { EditorFailure, MediaFailure, imageDelivery, loadEditor, productMedia, publishProduct, saveEditor, uploadProductImage, type EditorData } from '../../backend/admin/editor'
import { inrToPaise, slugify, validateEditor, type EditorForm, type EditorVariant } from '../../backend/admin/editor-model'
import { formatINR } from '../../backend/admin/product-model'
import { publicationReadiness } from '../../backend/admin/publication-model'
import { productImagePath } from '../../backend/public-product-media'
import './editor.css'
import './publication.css'

function Field({name,label,error,children}:{name:string;label:string;error?:string;children:ReactNode}){return <div className="editor-field"><label htmlFor={'editor-'+name}>{label}</label>{children}{error&&<p id={'error-'+name} className="editor-error">{error}</p>}</div>}
function Confirm({title,description,onStay,onConfirm,confirm='Discard Changes',stay='Stay',danger=true}:{title:string;description:ReactNode;onStay:()=>void;onConfirm:()=>void;confirm?:string;stay?:string;danger?:boolean}){
 const ref=useRef<HTMLDialogElement>(null)
 useEffect(()=>{const before=document.activeElement;ref.current?.showModal();return()=>{if(before instanceof HTMLElement)before.focus()}},[])
 return <dialog className="editor-dialog" ref={ref} aria-labelledby="editor-dialog-title" onCancel={e=>{e.preventDefault();onStay()}} onKeyDown={e=>{if(e.key==='Tab'){const buttons=ref.current?.querySelectorAll('button');if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}}><h2 id="editor-dialog-title">{title}</h2><div className="editor-dialog-body">{description}</div><div className="editor-actions"><button autoFocus className="admin-button" onClick={onStay}>{stay}</button><button className={`admin-button ${danger?'editor-danger':'editor-publish'}`} onClick={onConfirm}>{confirm}</button></div></dialog>
}
export function AdminProductEditor(){const {id}=useParams();return <Editor key={id??'new'} id={id}/>}
function Editor({id}:{id?:string}){
 const navigate=useNavigate(),location=useLocation()
 const [data,setData]=useState<EditorData>(),[form,setForm]=useState<EditorForm>(),[baseline,setBaseline]=useState(''),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState('')
 const [section,setSection]=useState(new URLSearchParams(location.search).get('section')==='variants'?'Variants':'Overview'),[errors,setErrors]=useState<Record<string,string>>({}),[error,setError]=useState(''),[notice,setNotice]=useState(location.state?.created?'Product draft created.':''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false)
 const [urls,setUrls]=useState<Record<string,string>>({}),[removeId,setRemoveId]=useState<string>(),[reloadPrompt,setReloadPrompt]=useState(false),[publishPrompt,setPublishPrompt]=useState(false),[recovery,setRecovery]=useState<string>(),[retry,setRetry]=useState<{file:File;request:string}>()
 const fileInput=useRef<HTMLInputElement>(null),allowNavigation=useRef(false),errorBox=useRef<HTMLDivElement>(null)
 const dirty=!!form&&JSON.stringify(form)!==baseline
 const blocked=useBlocker(({currentLocation,nextLocation})=>!allowNavigation.current&&(dirty||busy)&&currentLocation.pathname+currentLocation.search!==nextLocation.pathname+nextLocation.search)
 useBeforeUnload(e=>{if(dirty||busy){e.preventDefault();e.returnValue=''}})
 const refresh=async()=>{const next=await loadEditor(id);setData(next);setForm(next.form);setBaseline(JSON.stringify(next.form));setConflict(false);setErrors({});setError('')}
 useEffect(()=>{let cancelled=false;void loadEditor(id).then(next=>{if(!cancelled){setData(next);setForm(next.form);setBaseline(JSON.stringify(next.form));setLoading(false)}}).catch(()=>{if(!cancelled){setLoadError('Unable to load this product. Check your connection and access.');setLoading(false)}});return()=>{cancelled=true}},[id])
 useEffect(()=>{if(!id)return;let active=true;const read=()=>void imageDelivery(id).then(images=>{if(active)setUrls(Object.fromEntries(images.filter(i=>i.url).map(i=>[i.id,i.url!])))}).catch(()=>{if(active)setError('Private images could not be loaded. Use Refresh images to retry.')});read();const timer=setInterval(read,240000);return()=>{active=false;clearInterval(timer)}},[id,data])
 const set=<K extends keyof EditorForm>(key:K,value:EditorForm[K])=>{setForm(f=>f?{...f,[key]:value}:f);setNotice('')}
 const editable=!data?.product||(data.product.status==='draft'&&!data.product.sold_out_at)
 const attrs=(name:string)=>({id:'editor-'+name,'aria-invalid':!!errors[name],'aria-describedby':errors[name]?'error-'+name:undefined})
 const save=async()=>{
  if(!form||!data||busy||!editable)return
  const found=validateEditor(form);setErrors(found);setError('');setNotice('')
  if(Object.keys(found).length){setSection(Object.keys(found).some(k=>k.startsWith('variant'))?'Variants':found.production_limit?'Production':'Overview');setError('Review the highlighted fields.');requestAnimationFrame(()=>errorBox.current?.focus());return}
  setBusy(true)
  try{const savedId=await saveEditor(form,data.product);if(!id){allowNavigation.current=true;navigate('/admin/products/'+savedId+'/edit',{replace:true,state:{created:true}})}else{const next=await loadEditor(id);setData(next);setForm(next.form);setBaseline(JSON.stringify(next.form));setNotice('Changes saved.');setConflict(false)}}catch(e){setError(e instanceof Error?e.message:'Unable to save. Your changes are still here.');setConflict(e instanceof EditorFailure&&e.conflict)}finally{setBusy(false)}
 }
 const media=async(action:()=>Promise<unknown>,success:string)=>{setBusy(true);setError('');setNotice('');try{await action();await refresh();setRecovery(undefined);setRetry(undefined);setNotice(success)}catch(e){setError(e instanceof Error?e.message:'Image operation failed.');if(e instanceof MediaFailure&&e.result.orphan_path)setRecovery(e.result.orphan_path)}finally{setBusy(false)}}
 const upload=(file:File,request:string=crypto.randomUUID())=>{if(!id||!data?.product)return;setRetry({file,request});void media(()=>uploadProductImage(id,data.product!.updated_at,file,request),'Image uploaded.')}
 const refreshImages=()=>{if(id)void imageDelivery(id).then(images=>{setUrls(Object.fromEntries(images.filter(i=>i.url).map(i=>[i.id,i.url!])));setError('')}).catch(()=>setError('Images could not be refreshed. Please retry.'))}
 if(loading)return <section className="admin-panel editor-loading" role="status">Loading product editor…</section>
 if(loadError||!data||!form)return <section className="admin-panel editor-loading"><h1>Product unavailable</h1><p role="alert">{loadError}</p><button className="admin-button" onClick={()=>window.location.reload()}>Retry</button><Link className="admin-button" to="/admin/products">Back to Products</Link></section>
 const primary=form.images.find(i=>i.role==='primary')??form.images[0],imageUrl=primary?(urls[primary.id]??(primary.url.startsWith('storage://')?'':primary.url)):''
 const enabled=form.variants.filter(v=>v.enabled),category=data.categories.find(c=>c.id===form.category_id)
 const primaryVerified=!!primary&&(primary.url.startsWith('https://')||!!(id&&productImagePath(primary.url,id)&&urls[primary.id]))
 const readiness=publicationReadiness({name:form.name,slug:form.slug,designCode:form.design_code,pricePaise:inrToPaise(form.price)??0,productionLimit:Number(form.production_limit)||0,fitType:form.fit_type,categoryActive:!!category?.active,enabledVariants:enabled.length,invalidEnabledVariants:enabled.filter(v=>!v.sku.trim()||!v.size.trim()||(inrToPaise(v.price)??0)<=0).length,primaryImageUrl:primary?.url,primaryImageVerified:primaryVerified,produced:data.allocated,eligible:data.eligible,sold:data.sold,status:data.product?.status??'draft',archived:!!data.product?.archived_at,soldOut:!!data.product?.sold_out_at})
 const publish=async()=>{if(!id||!data.product||busy)return;setPublishPrompt(false);setBusy(true);setError('');try{await publishProduct(id,data.product.updated_at);await refresh();setNotice('Product published. It is now active and visible on the storefront.')}catch(e){setError(e instanceof Error?e.message:'Unable to publish. Reload and review readiness.');setConflict(e instanceof EditorFailure&&e.conflict)}finally{setBusy(false)}}
 const updateVariant=(index:number,patch:Partial<EditorVariant>)=>set('variants',form.variants.map((v,i)=>i===index?{...v,...patch}:v))
 const text=(key:keyof EditorForm,label:string,options:{readOnly?:boolean;multiline?:boolean;inputMode?:'decimal'|'numeric'}={})=><Field name={key} label={label} error={errors[key]}>{options.multiline?<textarea {...attrs(key)} rows={key==='full_description'?6:3} value={String(form[key])} readOnly={options.readOnly} onChange={e=>set(key,e.target.value)}/>:<input {...attrs(key)} value={String(form[key])} inputMode={options.inputMode} readOnly={options.readOnly} onChange={e=>{if(key==='name'&&!id&&form.slug===slugify(form.name)){setForm({...form,name:e.target.value,slug:slugify(e.target.value)});setNotice('')}else set(key,e.target.value)}}/>}</Field>
 const move=(index:number,direction:number)=>{const images=[...form.images];[images[index],images[index+direction]]=[images[index+direction],images[index]];set('images',images.map((image,i)=>({...image,sort_order:i})))}
 return <div className="product-editor">
  <AdminPageHeader title={id?'Edit Product':'Add Product'} description="Design details, variants and imagery. Every piece has a limit."/>
  <div className="admin-panel editor-toolbar"><Link className="editor-back" to="/admin/products"><ArrowLeft/> Products</Link><span>{dirty?'Unsaved changes':id?'All changes saved':'New draft'}</span><div className="editor-actions"><Link className="admin-button" to="/admin/products">Cancel</Link>{editable&&<button className="admin-button editor-save" disabled={busy||(!dirty&&!!id)} onClick={()=>void save()}><Save/>{busy?'Saving…':id?'Save Changes':'Save Draft'}</button>}</div></div>
  {!editable&&<p className="editor-notice">This {data.product?.status} design is read-only. Completed and archived designs cannot be restored or made saleable here.</p>}
  {notice&&<p role="status" className="editor-notice">{notice}</p>}
  {error&&<div ref={errorBox} tabIndex={-1} className="editor-error-box" role="alert"><p>{error}</p>{conflict&&<div className="editor-actions"><button className="admin-button" onClick={()=>setReloadPrompt(true)}>Reload latest data</button><button className="admin-button" onClick={()=>{setConflict(false);setError('')}}>Stay on page</button></div>}{recovery&&<button className="admin-button" disabled={busy} onClick={()=>void media(()=>productMedia({action:'cleanup',product_id:id!,orphan_path:recovery}),'Unassociated upload cleaned up. Select the image again to upload.')}>Retry cleanup</button>}{retry&&!recovery&&<button className="admin-button" disabled={busy||dirty} onClick={()=>upload(retry.file,retry.request)}>Retry upload</button>}</div>}
  <div className="editor-layout"><div className="admin-panel editor-main">
   <nav className="editor-tabs" aria-label="Product editor sections">{['Overview','Variants','Images','Production'].map(s=><button key={s} aria-pressed={s===section} onClick={()=>setSection(s)}>{s}{s==='Variants'&&<span>{form.variants.length}</span>}{s==='Images'&&<span>{form.images.length}</span>}</button>)}</nav>
   <fieldset disabled={!editable||busy} className="editor-fields"><legend className="sr-only">{section}</legend>
   {section==='Overview'&&<><h2>Product details</h2><p className="editor-help">Create a considered design. Save as a draft until inventory is ready.</p><div className="editor-form-grid">
    <div className="editor-wide">{text('name','Product Name')}</div>{text('slug','Slug',{readOnly:!!id})}{text('design_code','Design Code',{readOnly:!!id})}
    <p className="editor-wide editor-help">{id?'Slug and design code are permanent and cannot be changed.':'Choose a unique design code. Slug follows the name until you customize it; both become permanent on first save.'}</p>
    {text('price','Price (INR)',{inputMode:'decimal'})}{text('compare','Comparison Price (INR)',{inputMode:'decimal'})}
    <Field name="category_id" label="Category"><select {...attrs('category_id')} value={form.category_id} onChange={e=>set('category_id',e.target.value)}><option value="">Uncategorized</option>{data.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field>
    <Field name="fit_type" label="Fit"><select {...attrs('fit_type')} value={form.fit_type} onChange={e=>set('fit_type',e.target.value)}><option value="standard">Standard</option><option value="oversized">Oversized</option></select></Field>
    <div className="editor-wide">{text('short_description','Short Description',{multiline:true})}</div><div className="editor-wide">{text('full_description','Description',{multiline:true})}</div>
    <fieldset className="editor-wide editor-tag-list"><legend>Tags</legend>{data.tags.map(t=><label key={t.id}><input type="checkbox" checked={form.tags.includes(t.id)} onChange={e=>set('tags',e.target.checked?[...form.tags,t.id]:form.tags.filter(id=>id!==t.id))}/>{t.name}</label>)}</fieldset>
    {text('material','Material')}{text('style','Style')}<div className="editor-wide">{text('care_instructions','Care Instructions',{multiline:true})}</div><div className="editor-wide">{text('shipping_and_returns','Shipping and Returns',{multiline:true})}</div>
   </div></>}
   {section==='Variants'&&<><div className="editor-section-head"><div><h2>Color & size</h2><p className="editor-help">Saved variants can be disabled. Inventory is managed separately.</p></div><button className="admin-button" onClick={()=>set('variants',[...form.variants,{id:crypto.randomUUID(),colour_id:data.colours[0]?.id??'',size:'S',sku:'',price:form.price,compare:'',enabled:true,persisted:false,locked:false}])}><Plus/> Add Variant</button></div>
    {!form.variants.length&&<div className="editor-empty"><Package/><p>No variants yet. Add a color and size combination.</p></div>}
    <div className="editor-variants">{form.variants.map((v,i)=><section className="editor-variant" key={v.id} aria-label={'Variant '+(i+1)}><div className="editor-section-head"><h3>Variant {i+1}</h3>{!v.persisted&&<button className="admin-button" onClick={()=>set('variants',form.variants.filter(x=>x.id!==v.id))}><Trash2/> Remove</button>}</div><div className="editor-form-grid">
     <Field name={'colour-'+i} label="Color"><select id={'editor-colour-'+i} disabled={v.locked} value={v.colour_id} aria-describedby={errors['variant-'+i]?'error-variant-'+i:undefined} onChange={e=>updateVariant(i,{colour_id:e.target.value})}>{data.colours.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field>
     <Field name={'size-'+i} label="Size"><input id={'editor-size-'+i} list="editor-sizes" maxLength={20} readOnly={v.locked} value={v.size} onChange={e=>updateVariant(i,{size:e.target.value})}/></Field>
     <Field name={'sku-'+i} label="SKU"><input id={'editor-sku-'+i} readOnly={v.locked} value={v.sku} onChange={e=>updateVariant(i,{sku:e.target.value})} aria-invalid={!!errors['variant-'+i]} aria-describedby={errors['variant-'+i]?'error-variant-'+i:undefined}/></Field>
     <Field name={'vprice-'+i} label="Variant Price (INR)"><input id={'editor-vprice-'+i} inputMode="decimal" value={v.price} onChange={e=>updateVariant(i,{price:e.target.value})}/></Field>
     <Field name={'vcompare-'+i} label="Variant Comparison Price (INR)"><input id={'editor-vcompare-'+i} inputMode="decimal" value={v.compare} onChange={e=>updateVariant(i,{compare:e.target.value})}/></Field>
     <label className="editor-check"><input type="checkbox" checked={v.enabled} onChange={e=>updateVariant(i,{enabled:e.target.checked})}/>Enabled</label>
    </div>{!v.persisted&&<button className="admin-button" onClick={()=>updateVariant(i,{sku:[form.design_code||form.slug,data.colours.find(c=>c.id===v.colour_id)?.slug,v.size].join('-').toUpperCase()})}>Suggest SKU</button>}{v.persisted&&<p className="editor-help">{v.locked?'Color, size and SKU are locked by inventory or order history.':'Saved variants are retained for design history. Disable instead of removing.'}</p>}{errors['variant-'+i]&&<p className="editor-error" id={'error-variant-'+i}>{errors['variant-'+i]}</p>}</section>)}</div><datalist id="editor-sizes">{['S','M','L','XL'].map(s=><option key={s} value={s}/>)}</datalist>
   </>}
   {section==='Images'&&<><div className="editor-section-head"><div><h2>Product imagery</h2><p className="editor-help">JPG, PNG or WebP · Up to 10 MB per image</p></div><button className="admin-button" disabled={!id||dirty||busy||!!recovery} onClick={()=>fileInput.current?.click()}><ImagePlus/> Upload Image</button></div><input ref={fileInput} className="sr-only" type="file" aria-label="Choose product image" accept="image/jpeg,image/png,image/webp" disabled={!id||dirty||busy||!!recovery} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file);e.target.value=''}}/>
    {(!id||dirty)&&<p className="editor-help">Save the draft and any changes before uploading or removing images.</p>}
    {!form.images.length&&<div className="editor-empty"><ImagePlus/><p>No images yet. Your first upload becomes the primary image.</p></div>}
    <div className="editor-images">{form.images.map((image,i)=><article key={image.id} className="editor-image"><div className="editor-image-frame">{(urls[image.id]||!image.url.startsWith('storage://'))?<img src={urls[image.id]??image.url} alt={image.alt} onError={e=>{e.currentTarget.style.opacity='.2'}}/>:<Package aria-label="Image unavailable"/>}{image.role==='primary'&&<span className="admin-badge">Primary</span>}</div><Field name={'alt-'+image.id} label="Image description"><input id={'editor-alt-'+image.id} value={image.alt} onChange={e=>set('images',form.images.map(x=>x.id===image.id?{...x,alt:e.target.value}:x))}/></Field><div className="editor-image-actions"><button className="admin-button" disabled={image.role==='primary'} onClick={()=>set('images',form.images.map(x=>({...x,role:x.id===image.id?'primary':x.role==='primary'?'gallery':x.role})))}>Set Primary</button><button className="admin-button" disabled={i===0} aria-label={'Move image '+(i+1)+' earlier'} onClick={()=>move(i,-1)}><ArrowUp/></button><button className="admin-button" disabled={i===form.images.length-1} aria-label={'Move image '+(i+1)+' later'} onClick={()=>move(i,1)}><ArrowDown/></button><button className="admin-button editor-danger" disabled={dirty} onClick={()=>setRemoveId(image.id)}><Trash2/> Remove</button></div></article>)}</div>
   </>}
   {section==='Production'&&<><h2>A finite run. A lasting design.</h2><p className="editor-help">Each design has its own production limit. Quantities below are read-only.</p>{text('production_limit','Production Limit',{inputMode:'numeric',readOnly:data.allocated>0})}<p className="editor-help">{data.allocated>0?'Production limit is locked after production allocation begins.':'Set any positive whole number for this unallocated draft. 100 is only the default.'}</p><dl className="editor-metrics">{[['Allocated',data.allocated],['Sold',data.sold],['Run Remaining',Math.max(0,Number(form.production_limit||0)-data.allocated)],['Available to Sell',data.available]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></>}
   </fieldset>
   {section==='Images'&&id&&<button className="admin-button" onClick={refreshImages}>Refresh images</button>}
   {id&&<section className="editor-publication"><div className="editor-section-head"><h2>Publication readiness</h2>{readiness.ready?<span className="editor-ready">Ready</span>:<span className="editor-not-ready">Not ready</span>}</div><p className="editor-help">Publishing activates this design and makes it visible on the storefront.</p><ul>{readiness.checks.map(check=><li key={check.key} className={check.ready?'is-ready':''}>{check.ready?<CheckCircle2/>:<XCircle/>}<span><strong>{check.label}</strong><small>{check.detail}</small></span></li>)}</ul>{data.product?.status==='draft'?<button className="admin-button editor-publish" disabled={!readiness.ready||dirty||busy} onClick={()=>setPublishPrompt(true)}><Send/> Publish Product</button>:<p className="editor-help">This design is {data.product?.status}. Publication cannot be reversed here.</p>}{dirty&&<p className="editor-help">Save changes before publishing.</p>}</section>}
  </div><aside className="editor-aside"><section className="admin-panel editor-preview"><div className="editor-section-head"><h2>Admin preview</h2><AdminStatusBadge status={data.product?.status??'draft'}/></div><div className="editor-preview-image">{imageUrl?<img src={imageUrl} alt={primary?.alt??form.name}/>:<Package aria-label="No primary image"/>}</div><p className="editor-eyebrow">PERCENT · {form.fit_type} FIT</p><h3>{form.name||'Your next design'}</h3><strong className="editor-price">{inrToPaise(form.price)!==null?formatINR(inrToPaise(form.price)!):'₹—'}</strong><p className="editor-help">Production run · {form.production_limit||'—'} pieces</p>{data.product?.is_visible&&data.product.status!=='draft'?<Link className="admin-button" target="_blank" rel="noopener noreferrer" to={'/products/'+form.slug}>View on Store</Link>:<p className="editor-help">Draft or hidden products are not publicly visible.</p>}</section><section className="admin-panel editor-inventory"><h2>Inventory summary</h2><dl>{[['Variants',form.variants.length],['Allocated',data.allocated],['Sold',data.sold],['Run Remaining',Math.max(0,Number(form.production_limit||0)-data.allocated)],['Available',data.available]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><Link className="admin-button" to="/admin/inventory">Manage Inventory →</Link><p className="editor-help">Manage physical production and stock corrections in Inventory.</p></section></aside></div>
  {blocked.state==='blocked'&&<Confirm title="You have unsaved changes." description={busy?'An operation is still running. Stay until it finishes.':'Discard unsaved changes and leave this editor?'} onStay={()=>blocked.reset()} onConfirm={()=>{if(!busy)blocked.proceed()}}/>}
  {reloadPrompt&&<Confirm title="Reload latest data?" description="Your unsaved changes will be discarded." confirm="Reload latest data" onStay={()=>setReloadPrompt(false)} onConfirm={()=>{setReloadPrompt(false);setBusy(true);void refresh().catch(()=>setError('Unable to reload. Your changes are still here.')).finally(()=>setBusy(false))}}/>}
  {removeId&&<Confirm title="Remove product image?" description="This removes the image and its variant associations. Keep a copy before removing it." confirm="Remove Image" onStay={()=>setRemoveId(undefined)} onConfirm={()=>{const imageId=removeId;setRemoveId(undefined);void media(()=>productMedia({action:'delete',product_id:id!,image_id:imageId,expected_updated_at:data.product!.updated_at}),'Image removed.')}}/>}
  {publishPrompt&&<Confirm title={`Publish “${form.name}”?`} description={<><p>This immediately makes the design active and visible on the Percent storefront.</p><dl className="editor-publish-summary"><div><dt>Production</dt><dd>{data.allocated} / {form.production_limit}</dd></div><div><dt>Eligible stock</dt><dd>{data.eligible}</dd></div><div><dt>Enabled variants</dt><dd>{enabled.length}</dd></div></dl><p>This publication action cannot be reversed in the Admin Panel.</p></>} confirm="Publish Product" stay="Cancel" danger={false} onStay={()=>setPublishPrompt(false)} onConfirm={()=>void publish()}/>} 
 </div>
}

