import { useEffect,useState } from 'react'
import { Link,useOutletContext } from 'react-router-dom'
import { CheckCircle2,Clock3,CreditCard,PackageSearch,RefreshCw,Search,Truck } from 'lucide-react'
import type { AdminIdentity } from '../../components/admin/AdminRouteGuard'
import { AdminEmptyState,AdminPageHeader,AdminStatCard,AdminStatusBadge } from '../../components/admin/AdminComponents'
import { listAdminOrders,loadOrderMetrics } from '../../backend/admin/orders'
import { emptyOrderFilters,fulfillmentStatuses,money,orderCustomer,orderItemCount,orderMetrics,orderPageSize,orderStatuses,paymentStatuses,type AdminOrder,type OrderFilters } from '../../backend/admin/order-model'
import './orders.css'

const pretty=(value:string)=>value.replaceAll('_',' ')
const date=(value:string)=>new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))

function Filters({value,onChange}:{value:OrderFilters;onChange:(next:OrderFilters)=>void}){const set=(key:keyof OrderFilters,next:string)=>onChange({...value,[key]:next});return <div className="order-filters">
  <label><span>Order status</span><select value={value.status} onChange={e=>set('status',e.target.value)}><option value="all">All statuses</option>{orderStatuses.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select></label>
  <label><span>Payment</span><select value={value.payment} onChange={e=>set('payment',e.target.value)}><option value="all">All payments</option>{paymentStatuses.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select></label>
  <label><span>Fulfillment</span><select value={value.fulfillment} onChange={e=>set('fulfillment',e.target.value)}><option value="all">All fulfillment</option>{fulfillmentStatuses.map(v=><option key={v} value={v}>{pretty(v)}</option>)}</select></label>
  <label><span>Sort</span><select value={value.sort} onChange={e=>set('sort',e.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest total</option><option value="lowest">Lowest total</option></select></label>
</div>}

function OrderCards({orders}:{orders:AdminOrder[]}){return <div className="order-cards">{orders.map(order=>{const customer=orderCustomer(order);return <article key={order.id}><header><div><Link to={`/admin/orders/${order.id}`}>{order.order_reference}</Link><small>{date(order.created_at)}</small></div><AdminStatusBadge status={order.status}/></header><dl><div><dt>Customer</dt><dd>{customer.name}<small>{customer.email||'No email snapshot'}</small></dd></div><div><dt>Items</dt><dd>{orderItemCount(order)}</dd></div><div><dt>Total</dt><dd>{money(order.total_paise,order.currency)}</dd></div><div><dt>Payment</dt><dd>{pretty(order.payment_status)}</dd></div><div><dt>Fulfillment</dt><dd>{pretty(order.fulfillment_status)}</dd></div></dl><Link className="order-view" to={`/admin/orders/${order.id}`}>View order</Link></article>})}</div>}

export function AdminOrders(){
 const {user}=useOutletContext<AdminIdentity>();const [filters,setFilters]=useState(emptyOrderFilters),[search,setSearch]=useState(''),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[rows,setRows]=useState<AdminOrder[]>([]),[count,setCount]=useState(0),[metrics,setMetrics]=useState<ReturnType<typeof orderMetrics>>(),[loading,setLoading]=useState(true),[error,setError]=useState(false)
 useEffect(()=>{const t=setTimeout(()=>{setFilters(f=>({...f,search}));setPage(1)},250);return()=>clearTimeout(t)},[search])
 useEffect(()=>{const c=new AbortController();Promise.all([listAdminOrders(user.id,filters,page,c.signal),loadOrderMetrics(user.id,c.signal)]).then(([list,nextMetrics])=>{if(!c.signal.aborted){setRows(list.orders);setCount(list.count);setMetrics(nextMetrics);setError(false);setLoading(false)}}).catch(()=>{if(!c.signal.aborted){setError(true);setLoading(false)}});return()=>c.abort()},[user.id,filters,page,revision])
 const pages=Math.max(1,Math.ceil(count/orderPageSize));const changeFilters=(next:OrderFilters)=>{setLoading(true);setFilters(next);setPage(1)};const refresh=()=>{setLoading(true);setRevision(v=>v+1)}
 return <><AdminPageHeader title="Orders" description="Manage and review customer orders."/>
 <div className="admin-stats order-stats"><AdminStatCard label="Total Orders" value={String(metrics?.total??0)} note="All recorded orders" icon={PackageSearch}/><AdminStatCard label="Open Orders" value={String(metrics?.open??0)} note="Pending or confirmed" icon={Clock3}/><AdminStatCard label="Paid Orders" value={String(metrics?.paid??0)} note="Payment recorded as paid" icon={CreditCard}/><AdminStatCard label="Fulfilled" value={String(metrics?.fulfilled??0)} note="Delivered orders" icon={CheckCircle2}/></div>
 <section className="admin-panel order-list"><header><div><h2>All Orders</h2><p>Read-only order records and purchase-time snapshots.</p></div><button className="admin-icon-button" aria-label="Refresh orders" onClick={refresh}><RefreshCw/></button></header><label className="order-search"><Search/><span className="sr-only">Search orders</span><input aria-label="Search orders" placeholder="Order number, customer, email, or phone…" value={search} onChange={e=>{setSearch(e.target.value);setLoading(true)}}/></label><Filters value={filters} onChange={changeFilters}/>
 {loading?<div className="admin-loading" aria-busy="true"><p role="status">Loading orders…</p></div>:error?<div role="alert" className="order-error"><p>Unable to load orders.</p><button className="admin-button" onClick={()=>setRevision(v=>v+1)}>Retry</button></div>:rows.length?<><div className="order-table"><table><thead><tr><th>Order</th><th>Customer</th><th>Date</th><th>Items</th><th>Total</th><th>Payment</th><th>Fulfillment</th><th>Status</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{rows.map(order=>{const customer=orderCustomer(order);return <tr key={order.id}><td><strong>{order.order_reference}</strong></td><td>{customer.name}<small>{customer.email||customer.phone||'No contact snapshot'}</small></td><td>{date(order.created_at)}</td><td>{orderItemCount(order)}</td><td>{money(order.total_paise,order.currency)}</td><td><AdminStatusBadge status={order.payment_status}/></td><td><AdminStatusBadge status={order.fulfillment_status}/></td><td><AdminStatusBadge status={order.status}/></td><td><Link aria-label={`View ${order.order_reference}`} to={`/admin/orders/${order.id}`}>View</Link></td></tr>})}</tbody></table></div><OrderCards orders={rows}/></>:<AdminEmptyState icon={Truck} title={filters.search||filters.status!=='all'||filters.payment!=='all'||filters.fulfillment!=='all'?'No matching orders.':'No orders yet.'} description={filters.search||filters.status!=='all'||filters.payment!=='all'||filters.fulfillment!=='all'?'Try adjusting the search or filters.':'Customer orders will appear here once checkout is connected.'}/>}<footer><span>{count?`Showing ${(page-1)*orderPageSize+1}–${Math.min(page*orderPageSize,count)} of ${count}`:'0 orders'}</span><nav aria-label="Orders pagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page>=pages} onClick={()=>setPage(v=>v+1)}>Next</button></nav></footer></section></>
}
