import { useEffect, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { BarChart3, CalendarDays, IndianRupee, Package, RefreshCw, ShoppingBag, Tags, Users } from 'lucide-react'
import { AdminEmptyState, AdminPageHeader, AdminStatCard, AdminStatusBadge } from '../../components/admin/AdminComponents'
import { analyticsRangeLabels, loadAnalytics, type AnalyticsData, type AnalyticsRange, type AnalyticsTrend } from '../../backend/admin/analytics'
import { formatInrFromPaise } from '../../data/money'
import './analytics.css'

const integer=(value:number)=>new Intl.NumberFormat('en-IN').format(value)
const shortDate=(value:string,bucket:AnalyticsData['range']['bucket'])=>new Intl.DateTimeFormat('en-IN',bucket==='month'?{month:'short',year:'2-digit'}:{day:'numeric',month:'short'}).format(new Date(value))
const period=(data:AnalyticsData)=>data.range.all_time?'All recorded history':`${new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(data.range.start_at))} – ${new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(data.range.end_at))}`

type TrendMode='sales'|'orders'|'customers'
const trendMeta:Record<TrendMode,{label:string;read:(point:AnalyticsTrend)=>number;format:(value:number)=>string}>={sales:{label:'Confirmed sales',read:p=>p.confirmed_sales_paise,format:formatInrFromPaise},orders:{label:'Confirmed orders',read:p=>p.confirmed_orders,format:integer},customers:{label:'New customers',read:p=>p.new_customers,format:integer}}

function Comparison({current,previous}:{current:number;previous:number|null}){
 if(previous===null||previous===0)return <span className="analytics-comparison is-neutral">Previous period unavailable</span>
 const change=(current-previous)/previous*100
 return <span className={`analytics-comparison ${change>0?'is-up':change<0?'is-down':'is-neutral'}`}>{change>0?'+':''}{change.toFixed(1)}% vs previous period</span>
}

function TrendChart({data}:{data:AnalyticsData}){
 const [mode,setMode]=useState<TrendMode>('sales'),meta=trendMeta[mode],values=data.trend.map(meta.read),max=Math.max(...values,0)
 const points=max?values.map((value,index)=>`${data.trend.length===1?50:index/(data.trend.length-1)*100},${94-value/max*84}`).join(' '):''
 return <section className="admin-panel analytics-trend" aria-labelledby="analytics-trend-title"><header className="analytics-panel-head"><div><h2 id="analytics-trend-title">Performance Trend</h2><p>{data.range.bucket} buckets · confirmed commerce and customer joins</p></div><div className="analytics-tabs" role="group" aria-label="Trend metric">{(Object.keys(trendMeta) as TrendMode[]).map(key=><button key={key} aria-pressed={mode===key} onClick={()=>setMode(key)}>{trendMeta[key].label}</button>)}</div></header>
 {!max?<AdminEmptyState icon={BarChart3} title={`No ${meta.label.toLowerCase()} for this period.`} description="The chart will update when authoritative activity is recorded."/>:<div className="analytics-chart-wrap"><svg className="analytics-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`${meta.label} trend. Highest bucket ${meta.format(max)}.`}><title>{meta.label} over time</title><g aria-hidden="true">{[10,31,52,73,94].map(y=><line key={y} x1="0" x2="100" y1={y} y2={y}/>)}</g><polyline points={points}/>{values.map((value,index)=><circle key={data.trend[index].start_at} cx={data.trend.length===1?50:index/(data.trend.length-1)*100} cy={94-value/max*84} r="1.25"><title>{shortDate(data.trend[index].start_at,data.range.bucket)}: {meta.format(value)}</title></circle>)}</svg><div className="analytics-chart-axis"><span>{shortDate(data.trend[0].start_at,data.range.bucket)}</span><strong>{meta.format(max)} peak</strong><span>{shortDate(data.trend.at(-1)!.start_at,data.range.bucket)}</span></div></div>}
 <div className="analytics-trend-table" role="region" aria-label="Analytics trend values" tabIndex={0}><table><thead><tr><th scope="col">Period</th><th scope="col">Confirmed sales</th><th scope="col">Orders</th><th scope="col">New customers</th></tr></thead><tbody>{data.trend.map(row=><tr key={row.start_at}><th scope="row">{shortDate(row.start_at,data.range.bucket)}</th><td>{formatInrFromPaise(row.confirmed_sales_paise)}</td><td>{integer(row.confirmed_orders)}</td><td>{integer(row.new_customers)}</td></tr>)}</tbody></table></div></section>
}

function Summary({data}:{data:AnalyticsData}){const previous=data.summary.previous;return <div className="admin-stats analytics-stats">
 <div><AdminStatCard icon={IndianRupee} label="Confirmed Sales" value={formatInrFromPaise(data.summary.confirmed_sales_paise)} note="Paid and completed orders only"/><Comparison current={data.summary.confirmed_sales_paise} previous={previous?.confirmed_sales_paise??null}/></div>
 <div><AdminStatCard icon={ShoppingBag} label="Confirmed Orders" value={integer(data.summary.confirmed_orders)} note="Paid and completed"/><Comparison current={data.summary.confirmed_orders} previous={previous?.confirmed_orders??null}/></div>
 <div><AdminStatCard icon={Package} label="Units Sold" value={integer(data.summary.units_sold)} note="Confirmed order items"/><Comparison current={data.summary.units_sold} previous={previous?.units_sold??null}/></div>
 <div><AdminStatCard icon={Users} label="Customers" value={integer(data.summary.total_customers)} note={`${integer(data.summary.new_customers)} new in period`}/><Comparison current={data.summary.new_customers} previous={previous?.new_customers??null}/></div>
 </div>}

function OrderBreakdown({data}:{data:AnalyticsData}){const total=data.order_statuses.reduce((sum,row)=>sum+row.count,0);return <section className="admin-panel analytics-section"><header className="analytics-panel-head"><div><h2>Order Status</h2><p>All orders created in this period</p></div><Link to="/admin/orders">View orders</Link></header>{total?<div className="analytics-status-list">{data.order_statuses.map(row=>{const percent=row.count/total*100;return <article key={row.status}><div><AdminStatusBadge status={row.status}/><strong>{integer(row.count)}</strong><span>{percent.toFixed(1)}%</span></div><progress value={row.count} max={total} aria-label={`${row.status}: ${row.count} of ${total} orders`}/></article>})}</div>:<AdminEmptyState icon={ShoppingBag} title="No orders for this period."/>}</section>}

function CustomerAnalytics({data}:{data:AnalyticsData}){return <section className="admin-panel analytics-section"><header className="analytics-panel-head"><div><h2>Customers</h2><p>Canonical eligible customers</p></div><Link to="/admin/customers">View customers</Link></header><dl className="analytics-kpis"><div><dt>Total eligible</dt><dd>{integer(data.customers.total_eligible)}</dd></div><div><dt>New in period</dt><dd>{integer(data.customers.new_in_period)}</dd></div><div><dt>With confirmed orders</dt><dd>{integer(data.customers.with_confirmed_orders)}</dd></div><div><dt>Repeat customers</dt><dd>{integer(data.customers.repeat_customers)}</dd><small>At least 2 confirmed orders</small></div></dl></section>}

function InventoryAnalytics({data}:{data:AnalyticsData}){const rows=[['Available units',data.inventory.available_units],['Sold units',data.inventory.sold_units],['Withdrawn units',data.inventory.withdrawn_units],['Active products',data.inventory.active_products],['Production exhausted',data.inventory.production_exhausted_designs],['Sold out',data.inventory.sold_out_designs]];return <section className="admin-panel analytics-section"><header className="analytics-panel-head"><div><h2>Inventory Overview</h2><p>Current physical inventory state</p></div><Link to="/admin/inventory">View inventory</Link></header><dl className="analytics-kpis">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{integer(Number(value))}</dd></div>)}</dl><p className="analytics-note">Withdrawn units consume production capacity but are never counted as sold.</p></section>}

function TopProducts({data}:{data:AnalyticsData}){return <section className="admin-panel analytics-section analytics-wide"><header className="analytics-panel-head"><div><h2>Top Products</h2><p>Ranked by confirmed units sold</p></div><Link to="/admin/products">View products</Link></header>{data.top_products.length?<div className="analytics-table" role="region" aria-label="Top products" tabIndex={0}><table><thead><tr><th>Product</th><th>Units sold</th><th>Confirmed sales</th><th>Current production</th></tr></thead><tbody>{data.top_products.map(product=><tr key={product.product_id}><th scope="row"><Link to={`/admin/products/${product.product_id}/edit`}>{product.product_name}</Link></th><td>{integer(product.units_sold)}</td><td>{formatInrFromPaise(product.confirmed_sales_paise)}</td><td>{product.sold} sold · {product.withdrawn} withdrawn · {product.available} available</td></tr>)}</tbody></table></div>:<AdminEmptyState icon={Package} title="No confirmed product sales for this period." description="Pending orders and reservations are excluded."/>}</section>}

function ProductionAnalytics({data}:{data:AnalyticsData}){return <section className="admin-panel analytics-section analytics-wide"><header className="analytics-panel-head"><div><h2>Limited Production</h2><p>Configured capacity, immutable usage, and lifecycle state</p></div></header><div className="analytics-production">{data.production.map(product=><article key={product.product_id}><header><Link to={`/admin/inventory/${product.product_id}`}>{product.name}</Link><span>{product.used_percent}% used</span></header><progress value={product.used} max={product.production_limit} aria-label={`${product.name}: ${product.used} of ${product.production_limit} production used`}/><dl><div><dt>Limit</dt><dd>{product.production_limit}</dd></div><div><dt>Sold</dt><dd>{product.sold}</dd></div><div><dt>Withdrawn</dt><dd>{product.withdrawn}</dd></div><div><dt>Available</dt><dd>{product.available}</dd></div><div><dt>Remaining capacity</dt><dd>{product.remaining_capacity}</dd></div></dl><footer>{product.production_exhausted&&<AdminStatusBadge status="Production Exhausted"/>}{product.sold_out&&<AdminStatusBadge status="Sold Out"/>}{!product.production_exhausted&&!product.sold_out&&<AdminStatusBadge status={product.status}/>}</footer></article>)}</div></section>}

function CouponAnalytics({data}:{data:AnalyticsData}){return <section className="admin-panel analytics-section analytics-wide"><header className="analytics-panel-head"><div><h2>Coupon Performance</h2><p>Only redemptions attached to confirmed orders</p></div><Link to="/admin/coupons">View coupons</Link></header>{data.coupons.length?<div className="analytics-table" role="region" aria-label="Coupon performance" tabIndex={0}><table><thead><tr><th>Coupon</th><th>Confirmed redemptions</th><th>Discount granted</th><th>Confirmed sales</th></tr></thead><tbody>{data.coupons.map(coupon=><tr key={coupon.coupon_id}><th scope="row">{coupon.code}</th><td>{integer(coupon.redemptions)}</td><td>{formatInrFromPaise(coupon.discount_granted_paise)}</td><td>{formatInrFromPaise(coupon.confirmed_sales_paise)}</td></tr>)}</tbody></table></div>:<AdminEmptyState icon={Tags} title="No confirmed coupon redemptions for this period." description="Reserved or abandoned checkouts are excluded."/>}</section>}

export function AdminAnalytics(){
 const [params,setParams]=useSearchParams(),raw=params.get('range');const range:AnalyticsRange=raw==='7'||raw==='90'||raw==='all'?raw:'30'
 const [revision,setRevision]=useState(0),[state,setState]=useState<{range:AnalyticsRange;revision:number;data?:AnalyticsData;error?:boolean}>()
 useEffect(()=>{const controller=new AbortController();void loadAnalytics(range,controller.signal).then(data=>{if(!controller.signal.aborted)setState({range,revision,data})}).catch(()=>{if(!controller.signal.aborted)setState({range,revision,error:true})});return()=>controller.abort()},[range,revision])
 const current=state?.range===range&&state.revision===revision?state:undefined
 const setRange=(next:AnalyticsRange)=>setParams(previous=>{previous.set('range',next);return previous},{replace:true})
 const content=current?.data?<><Summary data={current.data}/><TrendChart data={current.data}/><div className="analytics-grid"><OrderBreakdown data={current.data}/><CustomerAnalytics data={current.data}/><InventoryAnalytics data={current.data}/><TopProducts data={current.data}/><ProductionAnalytics data={current.data}/><CouponAnalytics data={current.data}/></div></>:null
 return <><AdminPageHeader title="Analytics" description="Authoritative sales, customer, product, and production intelligence."><label className="admin-date-select"><CalendarDays/><span className="sr-only">Analytics date range</span><select value={range} aria-label="Analytics date range" onChange={event=>setRange(event.target.value as AnalyticsRange)}>{Object.entries(analyticsRangeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></AdminPageHeader><div className="admin-data-caption"><span>{current?.data?period(current.data):analyticsRangeLabels[range]} · confirmed commerce only</span><button className="admin-icon-button" aria-label="Refresh analytics" onClick={()=>setRevision(value=>value+1)}><RefreshCw/></button></div>{current?.error?<section className="admin-panel analytics-error" role="alert"><AdminEmptyState icon={BarChart3} title="Unable to load analytics." description="No values were estimated. Retry the authoritative request."/><button className="admin-button" onClick={()=>setRevision(value=>value+1)}>Retry <RefreshCw/></button></section>:content??<div className="admin-loading analytics-loading" aria-busy="true"><p role="status" className="sr-only">Loading analytics…</p><div className="admin-stats">{[0,1,2,3].map(value=><div className="admin-skeleton admin-stat" key={value}/>)}</div><div className="admin-skeleton analytics-skeleton"/></div>}</>
}
