import { useEffect, useRef, useState } from 'react'
import { Link, useBeforeUnload, useBlocker, useOutletContext, useParams } from 'react-router-dom'
import { Package, Layers, ShoppingBag, CheckCircle } from 'lucide-react'
import type { AdminIdentity } from '../../components/admin/AdminRouteGuard'
import { AdminPageHeader, AdminStatCard, AdminStatusBadge } from '../../components/admin/AdminComponents'
import { AllocationFailure, loadInventory, saveAllocation } from '../../backend/admin/inventory'
import { allocationEligible, allocationState, filterInventory, initialInventoryFilters, validateAllocation, type InventoryProduct } from '../../backend/admin/inventory-model'
import { AdjustmentDialog, InventoryHistory } from './InventoryAdjustments'
import { canAdjust } from '../../backend/admin/adjustment-model'
import './inventory.css'
function Progress({p}:{p:InventoryProduct}){return <div className="inventory-progress"><span>{p.allocated} / {p.production_limit} allocated</span><progress value={p.allocated} max={p.production_limit} aria-label={`${p.allocated} of ${p.production_limit} allocated`}/><span>{p.sold} / {p.production_limit} sold</span><progress value={p.sold} max={p.production_limit} aria-label={`${p.sold} of ${p.production_limit} sold`}/></div>}
function Identity({p}:{p:InventoryProduct}){return <div className="admin-product-identity"><span className="admin-product-thumb">{p.image?<img src={p.image} alt="" loading="lazy"/>:<Package aria-hidden="true"/>}</span><div><strong>{p.name}</strong><small>{p.design_code}</small></div></div>}
function Confirm({title,onStay,onConfirm}:{title:string;onStay:()=>void;onConfirm:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement;ref.current?.showModal();return()=>{if(previous instanceof HTMLElement)previous.focus()}},[]);return <dialog ref={ref} className="inventory-dialog" aria-labelledby="inventory-dialog-title" onCancel={e=>{e.preventDefault();onStay()}}><h2 id="inventory-dialog-title">{title}</h2><p>Discard your unsaved inventory values?</p><div className="inventory-actions"><button autoFocus className="admin-button" onClick={onStay}>Stay</button><button className="admin-button" onClick={onConfirm}>Discard</button></div></dialog>}
export function AdminInventory(){const {id}=useParams();const {user}=useOutletContext<AdminIdentity>();return <Inventory key={`${user.id}:${id??'list'}`} id={id} userId={user.id}/>}
function Inventory({id,userId}:{id?:string;userId:string}){
 const [data,setData]=useState<InventoryProduct[]>(),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[reload,setReload]=useState(false),[filters,setFilters]=useState(initialInventoryFilters),[values,setValues]=useState<Record<string,string>>({}),[baseline,setBaseline]=useState('{}')
 const [adjusting,setAdjusting]=useState<string>(),[adjustmentState,setAdjustmentState]=useState({dirty:false,busy:false})
 const adjustmentTrigger=useRef<HTMLButtonElement|null>(null)
 const inFlight=useRef(false);const p=data?.find(p=>p.id===id),dirty=JSON.stringify(values)!==baseline
 const blocked=useBlocker(({currentLocation,nextLocation})=>(dirty||busy||adjustmentState.dirty||adjustmentState.busy)&&currentLocation.pathname+currentLocation.search!==nextLocation.pathname+nextLocation.search)
 useBeforeUnload(e=>{if(dirty||busy||adjustmentState.dirty||adjustmentState.busy){e.preventDefault();e.returnValue=''}})
 const adopt=(rows:InventoryProduct[])=>{setData(rows);const product=rows.find(p=>p.id===id),v=Object.fromEntries(product?.variants.map(v=>[v.id,String(v.allocated)])??[]);setValues(v);setBaseline(JSON.stringify(v));setConflict(false);setError('')}
 useEffect(()=>{let active=true;void loadInventory(userId).then(rows=>{if(active){setData(rows);const product=rows.find(p=>p.id===id),v=Object.fromEntries(product?.variants.map(v=>[v.id,String(v.allocated)])??[]);setValues(v);setBaseline(JSON.stringify(v))}}).catch(()=>{if(active)setError('Unable to load inventory. Check your connection and access.')});return()=>{active=false}},[userId,id])
 const refresh=async()=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);try{adopt(await loadInventory(userId))}catch{setError('Unable to reload inventory. Please retry.')}finally{inFlight.current=false;setBusy(false);setReload(false)}}
 const save=async()=>{if(!p||inFlight.current)return;inFlight.current=true;setBusy(true);setError('');setNotice('');try{await saveAllocation(p,values);setBaseline(JSON.stringify(values));setNotice('Allocation saved.');try{adopt(await loadInventory(userId))}catch{setConflict(true);setError('Allocation saved, but refreshed values could not be loaded. Reload Latest before continuing.')}}catch(e){setError(e instanceof Error?e.message:'Unable to save allocation.');if(e instanceof AllocationFailure&&e.conflict)setConflict(true)}finally{inFlight.current=false;setBusy(false)}}
 const validation=p?validateAllocation(p,values):null,rows=filterInventory(data??[],filters)
 const controls=<button className="admin-button" disabled={busy} onClick={()=>dirty?setReload(true):void refresh()}>Reload Latest</button>
 return <>
 <AdminPageHeader title={id?'Production Allocation':'Inventory'} description="Manage production runs and variant allocation."/>
 {id&&<div className="inventory-actions"><Link className="admin-button" to="/admin/inventory">← Inventory</Link>{!error&&controls}</div>}
 {error&&<div className="admin-panel inventory-message" role="alert"><p>{error}</p>{controls}{conflict&&<button className="admin-button" onClick={()=>{setError('');setNotice('Your values are preserved. Reload Latest before saving.')}}>Stay on Page</button>}</div>}
 {notice&&<p role="status" className="inventory-message">{notice}</p>}
 {!data&&!error&&<p role="status">Loading inventory…</p>}
 {data&&!id&&<>
 <div className="admin-stats inventory-stats"><AdminStatCard label="Allocated Pieces" value={String(data.reduce((n,p)=>n+p.allocated,0))} note="Physical production units" icon={Layers}/><AdminStatCard label="Available to Sell" value={String(data.reduce((n,p)=>n+p.available,0))} note="Active, shop-enabled variants only" icon={Package}/><AdminStatCard label="Sold" value={String(data.reduce((n,p)=>n+p.sold,0))} note="Recorded sold pieces" icon={ShoppingBag}/><AdminStatCard label="Awaiting Allocation" value={String(data.filter(p=>p.status==='draft'&&p.remaining>0).length)} note="Draft designs with run capacity" icon={CheckCircle}/></div>
 <section className="admin-panel inventory-panel"><div className="inventory-heading"><div><h2>Product Inventory</h2><p>{data.length} designs · {data.reduce((n,p)=>n+p.variants.length,0)} variants</p></div>{controls}<Link className="admin-button" to="/admin/products/new">Add Product</Link></div>
 <div className="inventory-filters"><label>Search<input value={filters.search} placeholder="Product, slug, design code or SKU" onChange={e=>setFilters({...filters,search:e.target.value})}/></label>{(['allocation','lifecycle','availability','sort'] as const).map(key=><label key={key}>{key==='sort'?'Sort by':key}<select value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{(key==='allocation'?[['all','All allocation'],['Not Allocated','Not Allocated'],['Partially Allocated','Partial'],['Fully Allocated','Fully Allocated']]:key==='lifecycle'?[['all','All lifecycle'],['draft','Draft'],['active','Active'],['sold-out','Sold Out'],['archived','Archived']]:key==='availability'?[['all','All availability'],['available','Available to sell'],['low','Low availability'],['none','None available']]:[['name','Product name'],['newest','Newest'],['limit','Production limit'],['allocated','Most allocated'],['least','Least allocated'],['remaining','Lowest remaining'],['sold','Most sold']]).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>)}<button className="admin-button" onClick={()=>setFilters(initialInventoryFilters)}>Clear</button></div>
 <p className="inventory-note">Available to sell excludes drafts. Run remaining is unallocated capacity. Low availability means positive sellable stock at or below 10% of allocation.</p>
 {!rows.length?<p className="inventory-message">No matching inventory designs.</p>:<><div className="inventory-table" tabIndex={0} role="region" aria-label="Product inventory table"><table><thead><tr>{['Product','Lifecycle','Production','Sold','Available to Sell','Run Remaining','Allocation Status','Action'].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><Identity p={p}/></td><td><AdminStatusBadge status={p.status}/></td><td><Progress p={p}/></td><td>{p.sold}</td><td>{p.available}</td><td>{p.remaining}</td><td>{allocationState(p)}{p.remaining>0&&p.allocated>=p.production_limit*.9&&<small>Near limit</small>}</td><td><Link className="admin-button" to={`/admin/inventory/${p.id}`}>{allocationEligible(p)?'Manage Allocation':'View Inventory'}</Link></td></tr>)}</tbody></table></div><div className="inventory-cards">{rows.map(p=><article key={p.id}><Identity p={p}/><AdminStatusBadge status={p.status}/><Progress p={p}/><p>{p.available} available to sell · {p.remaining} run remaining</p><p>{allocationState(p)}</p><Link className="admin-button" to={`/admin/inventory/${p.id}`}>{allocationEligible(p)?'Manage Allocation':'View Inventory'}</Link></article>)}</div></>}
 <p className="inventory-note">Showing {rows.length} of {data.length} designs. {data.every(p=>p.allocated===0)&&'No production allocated yet.'}</p></section></>}
 {data&&id&&!p&&<section className="admin-panel inventory-message">Product unavailable.</section>}
 {p&&validation&&<div className="inventory-detail"><section className="admin-panel inventory-panel"><Identity p={p}/><AdminStatusBadge status={p.status}/><div className="inventory-metrics">{[['Production Limit',p.production_limit],['Allocated',p.allocated],['Sold',p.sold],['Available to Sell',p.available],['Physical Unsold / Unwithdrawn',p.physical],['Run Remaining',p.remaining]].map(([label,n])=><div key={label}><span>{label}</span><strong>{n}</strong></div>)}</div><Progress p={p}/><p>{allocationState(p)==='Fully Allocated'?'Production Run Fully Allocated':allocationState(p)}</p><p className="inventory-note">Physical pieces are permanent. Draft allocation does not publish a design or make it available to sell.</p><h2>Variant Inventory</h2><div className="inventory-variants">{p.variants.map(v=><article key={v.id}><div><strong>{v.colour} / {v.size}</strong><small>{v.sku} · {v.enabled?'Enabled':'Disabled'}</small>{!v.enabled&&<small>Allocation unavailable because this variant is disabled.</small>}</div><dl><div><dt>Allocated</dt><dd>{v.allocated}</dd></div><div><dt>Sold</dt><dd>{v.sold}</dd></div><div><dt>Available to Sell</dt><dd>{v.available}</dd></div><div><dt>Eligible Physical Stock</dt><dd>{v.physical}</dd></div><div><dt>Withdrawn</dt><dd>{v.withdrawn}</dd></div></dl>{canAdjust(p,v)&&<div className="adjustment-variant-actions"><button className="admin-button" disabled={dirty||busy} onClick={e=>{adjustmentTrigger.current=e.currentTarget;setAdjusting(v.id)}}>Adjust Stock</button>{dirty&&<small>Save or discard allocation changes first.</small>}</div>}</article>)}</div>{!p.variants.length&&<div className='inventory-message'><p>No variants have been created yet.</p><Link className='admin-button' to={'/admin/products/'+p.id+'/edit?section=variants'}>Add Variants</Link></div>}</section>
 <section className="admin-panel inventory-panel inventory-allocation"><h2>Production &amp; Allocation</h2><p>Configured production limit: <strong>{p.production_limit}</strong></p>{!allocationEligible(p)?<p role="status">Production allocation is read-only. {p.status==='archived'?'Archived designs are permanent.':p.remaining===0?'The production run is fully allocated.':'Allocation requires an eligible draft with enabled variants and no sale, withdrawal or order history.'}</p>:<form onSubmit={e=>{e.preventDefault();void save()}}><p className="inventory-note">Enter cumulative totals for each variant. Existing physical quantities cannot be reduced.</p>{p.variants.map(v=><label className="inventory-field" key={v.id} htmlFor={`allocation-${v.id}`}>{v.colour} / {v.size}<small>{v.sku} · currently {v.allocated}</small><input id={`allocation-${v.id}`} inputMode="numeric" value={values[v.id]??''} disabled={busy||!v.enabled} aria-invalid={!!validation.errors[v.id]} aria-describedby={validation.errors[v.id]?`allocation-error-${v.id}`:undefined} onChange={e=>setValues({...values,[v.id]:e.target.value})}/>{validation.errors[v.id]&&<span id={`allocation-error-${v.id}`} className="inventory-error">{validation.errors[v.id]}</span>}</label>)}<div className="inventory-live" aria-live="polite"><strong>{validation.total} / {p.production_limit} allocated</strong><p>{validation.errors.form??(validation.remaining===0?'Production Run Fully Allocated':`${validation.remaining} units remain unallocated.`)}</p></div><button className="admin-button" type="submit" disabled={busy||conflict||!dirty||Object.keys(validation.errors).length>0}>{busy?'Saving…':'Save Allocation'}</button></form>}</section></div>}
 {p&&<InventoryHistory product={p}/>} 
 {p&&adjusting&&p.variants.find(v=>v.id===adjusting)&&<AdjustmentDialog product={p} variant={p.variants.find(v=>v.id===adjusting)!} onClose={()=>{setAdjusting(undefined);requestAnimationFrame(()=>{if(adjustmentTrigger.current?.isConnected)adjustmentTrigger.current.focus();else document.getElementById('admin-workspace')?.focus()})}} onState={setAdjustmentState} onReload={async()=>{adopt(await loadInventory(userId))}} onSaved={async()=>{adopt(await loadInventory(userId));setNotice('Stock adjustment saved.')}}/>}
 {blocked.state==='blocked'&&<Confirm title="You have unsaved inventory changes." onStay={()=>blocked.reset()} onConfirm={()=>{if(!busy&&!adjustmentState.busy)blocked.proceed()}}/>}
 {reload&&<Confirm title="Reload latest inventory?" onStay={()=>setReload(false)} onConfirm={()=>void refresh()}/>}
 </>
}





