import { useEffect, useRef, useState, type Dispatch, type SetStateAction } from 'react'
import type { InventoryProduct, InventoryVariant } from '../../backend/admin/inventory-model'
import { adjustmentPreview, adjustmentReasons, blankAdjustment, type AdjustmentForm, type AdjustmentOperation } from '../../backend/admin/adjustment-model'
import { adjustStock, historyPageSize, loadAdjustmentHistory, type AdjustmentHistory } from '../../backend/admin/adjustments'
import { AllocationFailure } from '../../backend/admin/inventory'
import './adjustments.css'
export function AdjustmentDialog({product:p,variant:v,onClose,onSaved,onReload,onState}:{product:InventoryProduct;variant:InventoryVariant;onClose:()=>void;onSaved:()=>Promise<void>;onReload:()=>Promise<void>;onState:Dispatch<SetStateAction<{dirty:boolean;busy:boolean}>>}){
 const [form,setForm]=useState<AdjustmentForm>(blankAdjustment),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(false),[confirm,setConfirm]=useState<'close'|'reload'>(),[committed,setCommitted]=useState(false)
 const ref=useRef<HTMLDialogElement>(null),pending=useRef(false),dirty=!committed&&JSON.stringify(form)!==JSON.stringify(blankAdjustment),preview=adjustmentPreview(p,v,form)
 useEffect(()=>{const before=document.activeElement;ref.current?.showModal();return()=>{if(before instanceof HTMLElement)before.focus()}},[])
 useEffect(()=>{onState({dirty,busy});return()=>onState({dirty:false,busy:false})},[dirty,busy,onState])
 const close=()=>{if(busy)return;if(dirty)setConfirm('close');else onClose()}
 const reload=async()=>{if(pending.current)return;pending.current=true;setBusy(true);try{await onReload();onClose()}catch{setError('Unable to reload. Your entries are preserved.')}finally{pending.current=false;setBusy(false);setConfirm(undefined)}}
 const save=async()=>{if(pending.current||Object.keys(preview.errors).length||conflict)return;pending.current=true;setBusy(true);setError('');try{await adjustStock(p,v,form);setCommitted(true);try{await onSaved();onClose()}catch{setConflict(true);setError('Adjustment saved, but refreshing inventory failed. Reload Latest before continuing.')}}catch(e){setError(e instanceof Error?e.message:'Unable to save adjustment.');if(e instanceof AllocationFailure&&e.conflict)setConflict(true)}finally{pending.current=false;setBusy(false)}}
 const field=(key:keyof AdjustmentForm,value:string)=>setForm(f=>({...f,[key]:value}))
 return <dialog ref={ref} className="inventory-dialog adjustment-dialog" aria-labelledby="adjustment-title" onCancel={e=>{e.preventDefault();close()}}>
 <div className="inventory-heading"><h2 id="adjustment-title">Adjust Stock</h2><button className="admin-button" type="button" aria-label="Close adjustment" disabled={busy} onClick={close}>×</button></div>
 <p><strong>{p.name}</strong><br/>{v.colour} / {v.size}<br/><span className="adjustment-sku">{v.sku}</span></p>
 <dl className="adjustment-context">{[['Production Limit',p.production_limit],['Historical Produced',p.allocated],['Variant Sold',v.sold],['Variant Withdrawn',v.withdrawn],['Eligible Physical Stock',v.physical],['Run Remaining',p.remaining]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
 <p className="inventory-note">Eligible physical stock is unsold and unwithdrawn. Storefront availability stays lifecycle-gated. Withdrawals do not reopen production capacity.</p>
 {confirm?<section className="adjustment-confirm" aria-labelledby="adjustment-confirm-title"><h3 id="adjustment-confirm-title">Discard unsaved adjustment?</h3><p>Your quantity, reason and note will be discarded.</p><div className="inventory-actions"><button autoFocus className="admin-button" onClick={()=>setConfirm(undefined)}>Stay</button><button className="admin-button" disabled={busy} onClick={()=>confirm==='reload'?void reload():onClose()}>Discard</button></div></section>:<form onSubmit={e=>{e.preventDefault();void save()}}>
 <fieldset disabled={busy||committed}><legend>Adjustment</legend><label className="inventory-field">Operation<select value={form.operation} onChange={e=>field('operation',e.target.value as AdjustmentOperation)}>{[['INCREASE','Increase'],['DECREASE','Decrease'],['SET_EXACT','Set Exact']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
 <label className="inventory-field" htmlFor="adjustment-quantity">{form.operation==='SET_EXACT'?'Target Quantity':'Quantity'}<input autoFocus id="adjustment-quantity" inputMode="numeric" value={form.quantity} onChange={e=>field('quantity',e.target.value)} aria-invalid={!!preview.errors.quantity} aria-describedby="adjustment-quantity-error"/><span id="adjustment-quantity-error" className="inventory-error">{form.quantity&&preview.errors.quantity}</span></label>
 <label className="inventory-field" htmlFor="adjustment-reason">Reason (required)<select id="adjustment-reason" value={form.reason} onChange={e=>field('reason',e.target.value)} required aria-invalid={!form.reason} aria-describedby="adjustment-reason-help"><option value="">Choose reason</option>{adjustmentReasons.map(r=><option key={r}>{r}</option>)}</select><small id="adjustment-reason-help">A reason is required for the immutable history.</small></label>
 <label className="inventory-field" htmlFor="adjustment-note">Internal Note (optional)<textarea id="adjustment-note" value={form.note} onChange={e=>field('note',e.target.value)} maxLength={2000} rows={3} aria-invalid={!!preview.errors.note} aria-describedby="adjustment-note-error"/><span className="inventory-error" id="adjustment-note-error">{preview.errors.note}</span></label></fieldset>
 <div className="inventory-live" aria-live="polite"><p>Eligible Physical Stock: {preview.before} → {preview.after}</p><p>Historical Produced: {p.allocated} → {preview.produced}</p><p>Run Remaining: {p.remaining} → {preview.remaining}</p>{preview.errors.form&&<p className="inventory-error">{preview.errors.form}</p>}</div>
 {error&&<p className="inventory-error" role="alert">{error}</p>}{conflict&&<div className="inventory-actions"><button type="button" className="admin-button" disabled={busy} onClick={()=>dirty?setConfirm('reload'):void reload()}>Reload Latest</button><button type="button" className="admin-button" onClick={()=>setError('Your inputs are preserved. Reload Latest before saving again.')}>Stay on Page</button></div>}
 <div className="inventory-actions"><button className="admin-button" type="button" onClick={close} disabled={busy}>Cancel</button><button className="admin-button" type="submit" disabled={busy||committed||conflict||Object.keys(preview.errors).length>0}>{busy?'Saving…':'Save Adjustment'}</button></div>
 </form>}
 </dialog>
}
export function InventoryHistory({product:p}:{product:InventoryProduct}){
 const [variant,setVariant]=useState('all'),[operation,setOperation]=useState('all'),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[result,setResult]=useState<{key:string;data:AdjustmentHistory}>(),[error,setError]=useState('')
 const ids=variant==='all'?p.variants.map(v=>v.id):[variant],key=JSON.stringify([ids,operation,page,p.updated_at,revision]),loaded=result?.key===key
 useEffect(()=>{let active=true;const [selectedIds,selectedOperation,selectedPage]=JSON.parse(key) as [string[],string,number];void loadAdjustmentHistory(selectedIds,selectedPage,selectedOperation).then(data=>{if(active){setResult({key,data});setError('')}}).catch(()=>{if(active)setError('Unable to load inventory history.')});return()=>{active=false}},[key])
 const rows=loaded?result.data.rows:[],total=loaded?result.data.total:0
 return <section className="admin-panel inventory-panel"><h2>Inventory History</h2><p className="inventory-note">Immutable manual adjustments. Earlier allocation events remain in the per-piece audit log and are not relabeled as manual adjustments.</p><div className="inventory-filters"><label>History variant<select value={variant} onChange={e=>{setVariant(e.target.value);setPage(0)}}><option value="all">All Variants</option>{p.variants.map(v=><option key={v.id} value={v.id}>{v.colour} / {v.size}</option>)}</select></label><label>History operation<select value={operation} onChange={e=>{setOperation(e.target.value);setPage(0)}}><option value="all">All Operations</option>{['INCREASE','DECREASE','SET_EXACT'].map(o=><option key={o} value={o}>{o.replace('_',' ')}</option>)}</select></label></div>
 {error?<div role="alert"><p>{error}</p><button className="admin-button" onClick={()=>{setError('');setRevision(r=>r+1)}}>Retry history</button></div>:!loaded?<p role="status">Loading history…</p>:!rows.length?<p>No manual adjustments found.</p>:<div className="adjustment-history-scroll" tabIndex={0} role="region" aria-label="Inventory history"><table><thead><tr>{['Date','Variant / SKU','Operation','Change','Before','After','Reason / Note','Admin'].map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map(o=>{const v=p.variants.find(v=>v.id===o.variant_id),delta=o.after_quantity-o.before_quantity;return <tr key={o.id}><td><time dateTime={o.created_at}>{new Date(o.created_at).toLocaleString('en-IN')}</time></td><td>{v?.colour} / {v?.size}<small>{v?.sku}</small></td><td>{o.operation.replace('_',' ')}</td><td>{delta>0?'+':''}{delta}</td><td>{o.before_quantity}</td><td>{o.after_quantity}</td><td>{o.reason}<details><summary>Details</summary><p>{o.internal_note||'No internal note.'}</p><small>Operation: {o.id}</small></details></td><td><span title={o.actor_id}>{o.actorName}</span></td></tr>})}</tbody></table></div>}
 <div className="inventory-actions adjustment-pagination"><button className="admin-button" disabled={page===0||!loaded} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page+1}{loaded?` · ${total} operations`:''}</span><button className="admin-button" disabled={!loaded||(page+1)*historyPageSize>=total} onClick={()=>setPage(n=>n+1)}>Next</button></div></section>
}
